MongoEngine/mongoengine

AUTHORS, docs/changelog.rst, mongoengine/base/fields.py, tests/fields/fields.py
- Fields containing 'choices' of which a choice is an
EmbeddedDocument or Document will now accept subclasses of that
choice.
Includes unit tests.
- None. New feature only.
```python
from mongoengine import *
class Comments(EmbeddedDocument):
meta = {
'abstract': True
}
author = StringField()
message = StringField()
class UserComments(Comments):
pass
class BlogPost(Document):
comments = ListField(
GenericEmbeddedDocumentField(choices=(Comments,))
)
if __name__ == '__main__':
db = connect('FieldChoicesAcceptSubclasses')
BlogPost.drop_collection()
BlogPost(comments=[
UserComments(author='user2', message='message2'),
]).save()
db.drop_database('FieldChoicesAcceptSubclasses')
```
=> Field Choices Now Accept Subclasses of Documents

docs/changelog.rst, mongoengine/django/mongo_auth/models.py, tests/test_django.py
=> Fix #872: No module named 'django.utils.importlib' (Django dev)

docs/changelog.rst, mongoengine/queryset/transform.py, tests/queryset/queryset.py
=> Fix #863: Request Support for $min, $max Field update operators

docs/apireference.rst, docs/changelog.rst, mongoengine/base/datastructures.py, mongoengine/base/document.py, mongoengine/base/fields.py, mongoengine/common.py, mongoengine/dereference.py, mongoengine/document.py, mongoengine/fields.py, tests/fields/fields.py
Feedback and suggestions are always welcomed!
---
- Added new field type: EmbeddedDocumentListField.
- Provides additional query ability for lists of embedded documents.
- Closes MongoEngine/mongoengine#503.
Includes unit tests and updated documentation.
- None. New feature only.
```python
from mongoengine import *
class Comments(EmbeddedDocument):
author = StringField()
message = StringField()
class BlogPost(Document):
comments = EmbeddedDocumentListField(Comments)
if __name__ == '__main__':
db = connect('EmbeddedDocumentListFieldTestCase')
BlogPost.drop_collection()
post1 = BlogPost(comments=[
Comments(author='user1', message='message1'),
Comments(author='user2', message='message1')
]).save()    
post2 = BlogPost(comments=[
Comments(author='user2', message='message2'), …
```
=> EmbeddedDocumentListField (Resolves #503)

mongoengine/base/document.py
=> Use dict.pop() default argument instead of checking if the key exists ourselves

mongoengine/django/tests.py
If you run MongoDB with profiling enabled, one of the tests fails with a following error:
```
======================================================================
ERROR: test_mongo_test_case (tests.test_django.MongoTestCaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "mongoengine/django/tests.py", line 31, in tearDown
self.dropCollections()
File "mongoengine/django/tests.py", line 28, in dropCollections
self.db.drop_collection(collection)
File "/Users/wojcikstefan/Repos/mongoengine/env/lib/python2.7/site-packages/pymongo/database.py", line 490, in drop_collection
read_preference=ReadPreference.PRIMARY)
File "/Users/wojcikstefan/Repos/mongoengine/env/lib/python2.7/site-packages/pymongo/database.py", line 439, in …
```
=> Fix the unit tests for mongodb w/ profiling enabled

.travis.yml
Fixed pymongo versions to 2.7.2 and 2.8
The dev build for pymongo is the master branch which points to the new 3.0 driver.
Support for 3.0 will need to be added separately in the future as its a major version change and
will contain some backwards breaking changes
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/908)
=> Updated travis build

docs/changelog.rst, mongoengine/base/datastructures.py, tests/document/instance.py
fixes #914 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/920)
=> ListField of embedded docs doesn't set the _instance attribute when iterating over it

AUTHORS, docs/changelog.rst, mongoengine/base/document.py, mongoengine/dereference.py, tests/document/instance.py, tests/fixtures.py
Fixes #888:
- When de-pickling a document that is **not** dynamic, the _fields_ordered of the current type should be used
- When de-pickling a document that **is** dynamic, the pickled _fields_ordered should be used for the current document **ONLY**
Dereferencing Optimizations:
- Compiles the set of dbrefs as a set instead of a list so that conversions don't need to be made later
- Checks for resolved objects via dict `x in dict` instead of list `x in list`.
Below is a preview of how the dereferencing optimizations improved loading 500 documents:
name | # of operations | name | # or operations
------- | ---- | -------- | ---
..bson/objectid.py:288 ObjectId.__eq__ | 250998 | ..bson/objectid.py:288 ObjectId.__eq__  | 998
(This output was generated by GreenletProfiler)
The left shows the …
=> Major dereferencing optimizations and fix for de-pickling outdated documents [migrated 921]

AUTHORS, docs/changelog.rst, mongoengine/base/document.py, tests/document/delta.py
When id field presented in Embedded document, changes inside this document was ignored in method _get_changed_fields because it's id was added to inspected array before processing it fields.
Also modify unittests for _delta method, which fails without code modification.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/925)
=> _get_changed_fields fix for embedded documents with id field.

AUTHORS, docs/changelog.rst, mongoengine/base/document.py, tests/document/delta.py
fix mark_as_changed: rm lower level changed fields otherwise may cause conflict update error
this issue appears when retrieve from db
``` python
In [34]: class Foo(mongoengine.Document):
bar = mongoengine.DictField()
....:     
In [35]: Foo.objects.delete()
Out[35]: 1
In [36]: foo = Foo()
In [37]: foo.save()
Out[37]: <Foo: Foo object>
In [38]: foo = Foo.objects.first()
In [39]: foo.bar['what'] = 'ever'
In [40]: foo.bar['other'] = {}
In [41]: foo._changed_fields
Out[41]: ['bar.what', 'bar.other']
In [42]: foo.bar['other']['what'] = 'ever'
In [43]: foo._changed_fields
Out[43]: ['bar.what', 'bar.other', 'bar.other.what']
In [44]: foo.save()
---------------------------------------------------------------------------
OperationError                            Traceback (most recent call last) …
```
=> mark_as_changed issue

docs/changelog.rst, mongoengine/fields.py, tests/fields/fields.py
See issue #910 
This affects filtering/ordering of ComplexDateTimeField at microsecond-level granularity.
Also found that the "separator" option was not actually being used. Fixed that as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/911)
=> Fixed microsecond-level ordering/filtering bug with ComplexDateTimeField

.travis.yml, CONTRIBUTING.rst, README.rst, setup.cfg, setup.py, tox.ini
Mongoengine is tested on different PyMongo versions, different Python versions...
This pull-request add a ``tox.ini`` file allowing to run the test suite on every supported version composition .
This allow to do proper testing before submitting pull-requests without having to wait for TravisCI cross-versions testing.
To run the test in tox, simply run:
```shell
$ tox
```
It will create a virtualenv for each combination and run the same test suite (like TravisCI).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/960)
=> Tox support for cross-versions testing

docs/apireference.rst, mongoengine/base/document.py, mongoengine/document.py, mongoengine/errors.py, tests/document/instance.py, tests/fields/fields.py
This pull request try to fix #934 by adding an optionnal meta attribute: `strict`.
This attribute disable field existence check on data load, but not on constructor calls.
It also document both behaviors.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/957)
=> Allow to loads undeclared field with meta attribute (fix #934)

mongoengine/dereference.py, tests/document/delta.py
Fix for #931 issue. When model restored from database and there is a nested MapField there is an error in wrong key for changes when trying to add/change item in lower-level MapField.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/932)
=> fixed wrong _delta results on nested MapFields #931

mongoengine/base/fields.py, mongoengine/base/metaclasses.py, tests/document/validation.py
The 'owner_document' property of a Field now reflects the parent field which first contained the Field when a Document in inherited.
Fixes #954
Closes #955
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/976)
=> Reflect Inheritance in Field's 'owner_document'

docs/guide/defining-documents.rst
This was changed in https://github.com/MongoEngine/mongoengine/pull/62. It is present in versions > 0.7 http://docs.mongoengine.org/changelog.html#changes-in-0-7-0. I can reopen against an older branch if preferred.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/984)
=> Update docs with NotUniqueError

docs/upgrade.rst
This fixes rendering on the documentation website:
http://docs.mongoengine.org/upgrade.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/988)
=> Fix code formatting in upgrade doc

AUTHORS, docs/changelog.rst, mongoengine/document.py, tests/document/indexes.py
We shouldn't send any options to `collection.ensureIndex` that aren't supported by the index spec. See the unit test for more details.
Related to https://jira.mongodb.org/browse/SERVER-769
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/900)
=> Don't send a "cls" option to ensureIndex

docs/changelog.rst, docs/guide/querying.rst, mongoengine/queryset/transform.py, tests/queryset/queryset.py, tests/queryset/transform.py
problems with using operators names as field name #949
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/982)
=> Solution for #949

tests/fields/fields.py
Adds a unit test to exhibit the behavior of MongoDB when using a unique
multikey index. MongoDB treats any missing unique multikey index value
as NULL, thus throwing a Duplicate Key Error when saving multiple
missing values.
See #930 for more information.
- Closes #930
- Closes #952
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/995)
=> Unit Test - Unique Multikey Index

.travis.yml, AUTHORS, docs/changelog.rst, mongoengine/base/datastructures.py, mongoengine/base/metaclasses.py, mongoengine/connection.py, mongoengine/document.py, mongoengine/python_support.py, mongoengine/queryset/base.py, mongoengine/queryset/transform.py, mongoengine/queryset/visitor.py, tests/document/indexes.py, tests/fields/fields.py, tests/fields/geo.py, tests/queryset/geo.py, tests/queryset/queryset.py, tests/test_connection.py, tests/test_replicaset_connection.py
Hi guys,
Now everything is fixed and is fully compatible for both PyMongo 2.X and 3.X
I'm awaiting some feedback for:
1) ~~The way I introduced differential behaviour based on PyMongo version~~
2) ~~The behaviour for save() when a document is created with a given primary key, source of 5 of remaining issues. Here particularly, I have removed the check for self._created since we used to modify this why changing/switching db on the fly. This whole behaviour has changed in PyMongo3 and IMHO doesn't make sense anymore.~~
3) ~~Your opinion if the test_hint failure could point to a bug in PyMongo3~~
4) ~~A hand on the other error on test_geo_indexes_recursion~~
5) ~~A problem with binary field used as primary index that was always there and only discovered now by a better test that became …
=> Pymongo3 compatibility

tests/queryset/queryset.py
ref #570: this test would fail from v0.8.5 up, but passes on master.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1000)
=> added passing test for updates on related models

docs/guide/defining-documents.rst, mongoengine/base/document.py, mongoengine/document.py, tests/document/indexes.py
This PR is also not a "full strike" PR. ~~It will first need #946 to be merged, since it needs some Warning raising that are inside it.~~
I would like to add more serious warnings for the dropDups version, as some people may be surprised it is not supported anymore by MongoDB.
It also implements the remaining indexes types used with the shortcut +/-/$, by adding # for hashed, ( for geo2dsphere indexes and ) for geohaystack. [I've tried to use earth curve representation by the parenthesis for these geo-indexes, they were no other obvious symbols IMHO...]
Also, it allows to specify where one wants to have the "cls" index, by allowing something like ("field1", "cls", "field2"). We were forcing "cls" to be the first part of a compound key and this can be bad, for example when one has a …
=> Added hashed index, a bit more of geo-indexes, possibility to give _cls

docs/guide/defining-documents.rst
Solution for documentation issue #1003. The explanation about reverse_delete_rule was a bit mixed up.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1016)
=> Solution for documentation issue #1003

docs/changelog.rst, docs/guide/defining-documents.rst, mongoengine/base/document.py, mongoengine/base/metaclasses.py, mongoengine/document.py, tests/document/inheritance.py, tests/queryset/queryset.py
It's a pity we were waiting too long for tests for PR #688, so I decided to copy the logic and provide tests.
It allowed me to fix a couple other places too.
The tests also allowed me to find out that in one case, we are still messing up fields. I'll appreciate your input on this one
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/961)
=> Fixes and tests for default 'id' field creation in Document metaclass

mongoengine/base/document.py, mongoengine/base/metaclasses.py, mongoengine/document.py, mongoengine/fields.py, tests/fields/fields.py
Partial fix for #497 which IMHO is not completely legitime as a bug. At least, now each SequenceField counter will have the name of the abstract class and several abstract classes will not clash each other.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1026)
=> SequenceField for abstract classes now have a proper name

docs/changelog.rst, mongoengine/fields.py, tests/fields/fields.py
Fixes #652 url field validation too restrictive use django validation.
Updated to URL and Email regex validators, not rejecting IPv6. Added schemes argument to URL validation, to be able to specify any scheme different from http(s) or ftp(s), like ws or else
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1028)
=> Updated URL and Email regex validators, added schemes to url validator

mongoengine/base/fields.py, tests/queryset/queryset.py
added new test like defined in issue #712 and changed ObjectIdField to_python() method to use a try except similar to other Field classes.
This PR is not making consensus. You may read the history of Pros and Contras in the closed PR #830 
Sorry for creating a new PR, I had to bring that to a new branch
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/936)
=> changed ObjectIdField to_python() method to avoid crash, issue 712

docs/changelog.rst, docs/guide/defining-documents.rst, mongoengine/document.py, tests/document/instance.py
Fixes #1011 not only for default document size (also updated in the docs), but also for any given size which may not be a multiple of 256
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1031)
=> CappedCollection max_size normalized to multiple of 256

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/queryset.py
Closes #569 
@MRigal here's the implementation of sum & average using the aggregation framework. I haven't tested it in a sharded environment, but if it works, I believe it could fully replace the slower, map-reduce-based `BaseQuerySet.sum` and `BaseQuerySet.average`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1021)
=> aggregate_sum/average + unit tests

AUTHORS, docs/changelog.rst, mongoengine/document.py, tests/test_signals.py
this feature is useful when we update the switched collection and want to send signals. 
e.g: we have a template collection named "user", we have collections create from "user"  named "user__1","user__2","user__N".
when we update "user__N", we have to set self._created = False after call `switch_collection()`, this is a bad practice.  if we forget do this.  the `singal.post_save`'s `created` argument  will always be True.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1020)
=> improve _created status when switch collection and db

AUTHORS, docs/changelog.rst, mongoengine/queryset/base.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1046)
=> Delete cascade cycle issue

AUTHORS, docs/changelog.rst, mongoengine/fields.py, tests/fields/fields.py
CachedReferenceField creates DBRef on to_python, but can't save them on to_mongo.
Dereferencing DBRef to document type before returning it from to_python.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1048)
=> Suggested fix for #1047: CachedReferenceField DBRefs bug

docs/changelog.rst, mongoengine/queryset/base.py, tests/document/indexes.py, tests/queryset/queryset.py
fixes #842
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1049)
=> fix-#842: Fix ignored chained options

mongoengine/base/fields.py, mongoengine/fields.py, tests/fields/fields.py
I tried to use GenericReferenceField with the choices param and had some issues:
- cannot define allowed Documents by there name
- in case  you didn't dereference a GenericReferenceField present in a document, the choices validation failed given the field contained a dict containing the _cls and DBRef instead of the actual document
So here is my patch waiting for a review ;-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1060)
=> Fix GenericReferenceField choices parameter

docs/changelog.rst, mongoengine/document.py, mongoengine/errors.py, tests/document/instance.py
Hi there,
Working with `save_condition` in save, I realised using an `OperationError` exception is too vague when trying to return fine errors to client, example:
```python
class Doc(Document):
version = fields.IntField(default=1)
field = fields.StringField(unique=True)
doc_1 = Doc(field='unique').save()
try:
doc_2 = Doc(field='unique').save() # raises NotUniqueError, subclass of OperationError
except OperationError:
pass
doc_1.field = 'two'
http_if_match = 42 # Client provide If-Match header in HTTP request
try:
doc_1.save(save_condition={'version': http_if_match}) # raises OperationError
except OperationError:
pass
```
I solve this by replacing the `OperationError` triggered by an invalid `save_condition` by a new `SaveConditionError` (subclass of `OperationError`, to mimic the …
=> Use SaveConditionError instead of OperationError in save_condition

docs/guide/querying.rst
Current documentation does not consider performance issues in using len instead of count.
https://github.com/MongoEngine/mongoengine/issues/937
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1087)
=>  QuerySet count vs len #937

mongoengine/connection.py
Only MongoReplicaSetClient uses hosts_or_uri param and it will be deprecated soon.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1055)
=> comply to pymongo MongoClient constructor host

docs/guide/text-indexes.rst
The correct name for MongoDB text search index definition property is "weights" not "weight". Using "weight" will cause "Index with name ... already exists with different options". This is misleading and has to be changed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1084)
=> Bad property name for text search index meta

mongoengine/fields.py, tests/fields/fields.py
Following issue #1058
The fix is pretty simple: set `_auto_dereference` to `False` in DictField `__init__`
However I'm wondering why the `__get__` method with dereferencing functionality are in so many places (`ComplexBaseField`, `ReferenceField`, `CachedReferenceField`, `GenericReferenceField`).
From my point of view, their should be a single `Dereferencable` wich implement this special `__get__` method. Class which should be subclassed by the reference related fields only.
@MRigal This part of the code is not simple to understand, so it's possible I'm missing a point (or the actual behavior is already more or less what I'm saying), so what do you think of this ?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> Fix DictField with '_cls' field is converted to Document on access

docs/changelog.rst, mongoengine/base/document.py
fixes #1105
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1113)
=> fix-#1105: StrictDict & SemiStrictDict are shadowed at init time

AUTHORS, docs/changelog.rst, setup.py, tox.ini
This patch makes a small but impactful adjustment to the way mongoengine is installed and tested. The result is that `nose` and `rednose` are now no longer required for production installations of mongoengine. Test run semantics and behavior should remain unchanged.
Addresses issue https://github.com/MongoEngine/mongoengine/issues/1079. [Pull request #1082](https://github.com/MongoEngine/mongoengine/pull/1082) attempted to fix this, but it seems to have stalled as of 2.5 months ago.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1121)
=> Move nose/rednose from install dependencies to test dependencies

docs/changelog.rst, mongoengine/queryset/transform.py, tests/queryset/queryset.py
The following example query would have failed to compile:
```
Bar.objects(foo__elemMatch={'shape': "square", "color__exists": True})
```
This adds support for this query.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1117)
=> Enable ops in queries using elemMatch for EmbeddedDocuments

AUTHORS, docs/changelog.rst, mongoengine/document.py, tests/document/instance.py
This implements shard keys on embedded documents (#551).
The implementation here doesn't notice that you've tried to change the shard key until you save the document (though it still works as before when the shard key is on the toplevel document).  I don't see a straightforward way to detect the changed shard keys earlier, so I'm leaving it like this for now, but I can try to come up with a way if you think it's necessary.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1158)
=> Allow shard key to be in an embedded document (#551)

docs/guide/defining-documents.rst, mongoengine/base/fields.py
Please consider this patch.  It:
* **Removes special cases.**  The former `verbose_name`, `help_text`, and `custom_data` special cases have been removed and are fully covered/supported by this change.  Those test cases didn't even need to change, and it's likely advisable to continue to document _de-facto_ standard labels for new users.
* **Saves space.**  Only store metadata you actually care about, i.e. saves three `None` associations on every field if you, like me, don't use the aforementioned metadata in every project.  As `__slots__` is not in use, those would be stored in the `self.__dict__` mapping.  (Which is what this patch updates flexibly instead.)
* **Removes unnecessary indirection.**  Additionally, every access to that metadata requires at least an extra attribute lookup, …
=> Indirection-free optimized field metadata.

mongoengine/fields.py
When I first tried to use the `reverse_delete_rule` feature of
`ReferenceField`, I had to dig through the source code to find what the
actual integer values were expected to be for DO_NOTHING, NULLIFY,
CASCADE, DENY, and PULL (or at least, where these constants were defined
so that I could import and use them). This patch adds the integer values
for those constants (which are defined in mongoengine.queryset.base) to
the docs so that users can easily choose the correct integer value.
Note: A possible improvement on this change would be to include
`mongoengine.queryset.base` module documentation in the generated docs,
and then update the `ReferenceField` docs to link to the documentation
of these constants (DO_NOTHING, NULLIFY, etc.). 
[If you'd like me to do this instead of the current …
=> fields.ReferenceField: add integer values to `reverse_delete_rule` docs

AUTHORS, docs/changelog.rst, mongoengine/fields.py, tests/fields/fields.py
Documents can now reference abstract types, and refer to any Document that inherits from the type. For example:
```python
class Sibling(Document):
name = StringField()
meta = {"abstract": True}
class Sister(Sibling):
pass
class Brother(Sibling):
sibling = ReferenceField(Sibling)
class Mother(Document):
name = StringField()
```
In this situation, a Brother can store an instance of a Sister or a Brother in the `sibling` field, and retrieve the same Sister or Brother, through the same field, as a full object (and not a Sibling object).
Storing a Document in a reference field of an abstract type will fail validation, however, if the Document does not inherit from the abstract type specified on the ReferenceField. Thus trying to store a Mother on the `sibling` field of Brother, will fail …
=> ReferenceFields can now reference abstract Document types

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/queryset.py
I noticed something disturbing in our query logs earlier today - some of the queries were incorrectly routed to the primary when using `ReadPreference.SECONDARY`. Eventually, it came to my realization that `read_preference` wasn't working if it was put after `limit`, `skip`, or `hint` (and probably some other methods that allow chaining).
Note: As of now, the fix only works for pymongo ver < 3.0. I think `read_preference` is **completely** broken with ver >= 3.0, but I don't have full clarity on the situation yet. It seems that `self._collection.find` doesn't accept `read_preference` as a valid kwarg any more and if I'm reading pymongo's docs right, you can only set read preference on a client/database/collection, not a particular cursor. It doesn't seem to be set either way:
```
In [10]: …
```
=> Fix read_preference

AUTHORS, docs/changelog.rst, mongoengine/connection.py, tests/test_connection.py
Using `mongomock://` scheme in URI enables the mocking. Fix #1045.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1151)
=> Add support for mocking MongoEngine based on mongomock

docs/guide/index.rst, docs/guide/mongomock.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1180)
=> Added page for documenting mongomock. Updated docs/guide/index.rst

docs/code/tumblelog.py
when I run this demo.
The following throws two errors:
```python
from mongoengine import *
connect('tumblelog')
class Comment(EmbeddedDocument):
content = StringField()
name = StringField(max_length=120)
class User(Document):
email = StringField(required=True)
first_name = StringField(max_length=50)
last_name = StringField(max_length=50)
class Post(Document):
title = StringField(max_length=120, required=True)
author = ReferenceField(User)
tags = ListField(StringField(max_length=30))
comments = ListField(EmbeddedDocumentField(Comment))
class TextPost(Post):
content = StringField()
class ImagePost(Post):
image_path = StringField()
class LinkPost(Post):
link_url = StringField()
Post.drop_collection()
john = User(email='jdoe@example.com', first_name='John', last_name='Doe')
john.save()
post1 …
```
=> fix for docs.code.tumblelog.py

docs/changelog.rst, tox.ini
On windows, pip needs the PYTHON_EGG_CACHE and windir environment variables to be able to install packages correctly. Therefore tox needs to pass these variables down to pip when tox installs packages locally.
PYTHON_EGG_CACHE is set to reside in the virtualenv directory so that it does not pollute a users global egg cache directory. Plus it may not be set by a user, even though I found it to be required for pip to run in virtualenv with tox.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1153)
=> Fixed not being able to run tests on Windows

docs/changelog.rst, mongoengine/base/document.py, tests/document/indexes.py
As of MongoDB 2.6, sparse compound indexes are allowed: <http://docs.mongodb.org/manual/core/index-sparse/#sparse-compound-indexes>.  This removes the explicit check prohibiting sparse compound indexes.  Also, I added a unit test to make sure that sparse-compound indexes work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1114)
=> Allow sparse compound indexes

AUTHORS, docs/changelog.rst, mongoengine/base/document.py, mongoengine/base/fields.py, mongoengine/fields.py, tests/document/instance.py, tests/fields/fields.py
Addresses #1217.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1218)
=> Curry **kwargs through to_mongo on fields

mongoengine/base/fields.py, mongoengine/document.py, mongoengine/fields.py, mongoengine/queryset/base.py, mongoengine/queryset/transform.py, setup.py, tests/document/inheritance.py
Empty _except:_ clauses catch too many exceptions, for example, KeyboardInterrupt and SystemExit.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1241)
=> Fixed too broad exception clauses in the project

mongoengine/fields.py
in `ReferenceField()` comments, the given demo codes has a small bug.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1235)
=> fix a small bug - ReferenceField() comment give a wrong demo .

docs/guide/defining-documents.rst
The 'defining a document' section currently doesn't include EmbeddedDocumentListField. Only EmbeddedDocumentField
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1183)
=> Add EmbeddedDocumentListField to user guide

docs/changelog.rst, mongoengine/fields.py, tests/queryset/queryset.py
fixes #1187
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1188)
=> fix-#1187: count on ListField of EmbeddedDocumentField fails

mongoengine/fields.py, requirements.txt, setup.py, tests/fields/fields.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1240)
I thought about decimal support too, but large decimals are being converted to float as 'infinity' implicitly. Also, if one uses decimals for some reason, one is likely going to use DecimalField.
=> Added support for long values in FloatFields

AUTHORS, docs/changelog.rst, mongoengine/base/datastructures.py, tests/fields/fields.py
If you `__setitem__` in BaseList with a negative index and then try to save this, you will get an error like: 
OperationError: Could not save document (cannot use the part (shape of signal.shape.-1) to traverse the element ({shape: [ 0 ]})).
To fix this I rectify negative list indices in BaseList _mark_as_changed as the appropriate positive index. This fixes the above error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1270)
=> Bug fixed accessing BaseList with negative indices

AUTHORS, docs/changelog.rst, mongoengine/base/document.py, tests/document/instance.py
When an EmbeddedDocument is initialized with positional arguments, the
document attempts to read _auto_id_field attribute which may not exist
and would throw an AttributeError exception and fail the initialization.
This change and the test is based on the discussion in issue #681 and
PR #777 with a number of community members.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1277)
=> Fix AttributeError when initializing EmbeddedDocuments

mongoengine/base/datastructures.py, tests/fields/fields.py
Regression test included.
May fix the second part of the issue #1250.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1271)
=> Fixes unicode bug in EmbeddedDocumentListField

mongoengine/queryset/base.py
it is obvious that we should set `no_cursor_timeout` to `not ` `timeout`
this issue was exposed in our mongod with server stats of high opened noTimeout cursors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1304)
=> Fix no_cursor_timeout with pymongo3

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/queryset.py
As discussed in #1021
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1336)
=> Replace map-reduce based QuerySet.sum/average with aggregation-based implementations

mongoengine/fields.py
Fix example in the docs for regsiter_delete_rule. See issue #1339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1340)
=> fix example for register_delete_rule. see issue #1339

mongoengine/base/document.py
Synthetic benchmark showed that `set() - set()` in this case is around twice faster than looping and checking existence. In real life profiling showed less but:
```
../document.py:40 Attribute.__init__  17727  3.436296  20.03336  0.001130
../document.py:40 Attribute.__init__  2820   0.502591  3.044738  0.001080
```
Last column is average time per call so it's ~4% when creating mongoengine objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1346)
=> Speed up checking if we passed missing field

mongoengine/connection.py, tests/test_connection.py
Fixes a regression caused by #1151 where host can no longer be a list when calling connect() as this triggers the following error:
```
mongoengine/connection.py line 61 in register_connection
if conn_host.startswith('mongomock://'):
AttributeError: 'list' object has no attribute 'startswith'
```
Adds a new unit test to cover this possibility and follows the same approach used by pymongo.MongoClient, which is designed to accept host as either a list or a string.
=> Fix connecting to a list of hosts

README.rst, setup.cfg, setup.py, tox.ini
Removing `rednose` from the tests fixes Python 2.6 tests. I reported this issue to `rednose` in https://github.com/JBKahn/rednose/issues/9. For now, I think it makes sense to remove this package. Less code = better.
If we merge this PR along with #1390, the build status for this package is *finally* going to be green! 🎆
=> Fix Python 2.6 tests

mongoengine/queryset/base.py, tests/queryset/pickable.py
Added support for pickling BaseQueryset instances
=> Fixed issue https://github.com/MongoEngine/mongoengine/issues/442

AUTHORS, docs/changelog.rst
Added info in CHANGELOG about this pull request: https://github.com/MongoEngine/mongoengine/pull/1397
=> Add info in CHANGELOG 

docs/guide/defining-documents.rst
At Dictionary Fields description, it seems that the intent of the sentence make more sense by adding : "not".
=> Dictionnary Field recommended use

.travis.yml, mongoengine/__init__.py, mongoengine/base/datastructures.py, mongoengine/base/document.py, mongoengine/base/fields.py, mongoengine/base/metaclasses.py, mongoengine/dereference.py, mongoengine/document.py, mongoengine/fields.py, mongoengine/queryset/__init__.py, mongoengine/queryset/base.py, mongoengine/queryset/queryset.py, mongoengine/queryset/transform.py, mongoengine/signals.py, requirements.txt, setup.cfg, setup.py, tests/document/indexes.py, tests/queryset/queryset.py, tests/queryset/transform.py, tests/queryset/visitor.py, tox.ini
Includes running flake8 and flake8-import-order during the travis run (only for Python 2.7 for now) and all the tweaks necessary to make it pass.
None of the logic has changed, so this should be safe to merge once the tests pass.
=> Improve health of this package

mongoengine/queryset/base.py, tests/queryset/queryset.py
Fixes #1415 
@lafrech @zeezdev take a look please
=> Fix BaseQuerySet#sum and BaseQuerySet#average for fields that specify a db_field

mongoengine/document.py, tests/document/instance.py
This PR adds a test for creating and updating a document that has a `False`y `primary_key` attribute, and fixes it by replacing Boolean-casting existential checks for non-casting checks for `NoneType`.
Closes #1352.
=> Support Falsey `primary_key`s

tests/document/indexes.py
It was introduced as an attempt to fix randomly failing tests and was never reverted (though @gilbsgilbs tried in #1269)
=> Remove unnecessary randomness in indexes tests

mongoengine/fields.py, tests/queryset/queryset.py
Previously filtering by `embedded_doc=None` would raise an `AttributeError` in `EmbeddedDocumentField.prepare_query_value`.
Inspired by #1163 (thanks @decklord!).
=> Fix filtering by embedded_doc=None

mongoengine/queryset/base.py, tests/queryset/queryset.py
See https://docs.mongodb.com/manual/reference/method/cursor.comment/#cursor.comment for details.
Inspired by #1231 (thanks @scorday!) + added a unit test
=> Add support for cursor.comment

mongoengine/base/document.py, tests/fields/fields.py
Unit test inspired by #1279 (thanks @julianwachholz)
This fixes a bug left behind by #625 where the initial implementation required to set the `get_<field>_display` methods on the class and not the instance (because of `__slots__`). However, the PR later took a different approach and never corrected this issue.
@lafrech @julianwachholz take a look please.
=> Fix doc.get_<field>_display

mongoengine/base/datastructures.py, tests/test_datastructures.py
=> Fix __repr__ method of the StrictDict

mongoengine/queryset/base.py, mongoengine/queryset/queryset.py, tests/queryset/queryset.py
Without these fixes, iterating over a queryset within another iteration would cause the "outer" iteration to only return 100 results.
This PR also fixes #1086 where calling `len(qs)` mid-iteration would cause the same problem.
Thanks to @eli-b and @gordol for inspiration!
=> Fix iteration within iteration

mongoengine/queryset/base.py, tests/queryset/queryset.py
=> Implement BaseQuerySet.batch_size

mongoengine/queryset/base.py
replace literal 'id__in' with 'pk__in'
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1247)
=> fix delete cascade for models without literal `id` field

docs/upgrade.rst
Hi!
I was a bit confused by this undocumented breaking change from 0.10.6 to 0.10.7. I had to dig into the project commits to understand what actually hapenned. Even the changelog is not that clear. Moreover, old aggregate_* methods could have been backported, pending a major version update (where we expect breaking changes).
Thanks!
=> Upgrade notice for 0.10.7

mongoengine/connection.py
* Stop the unnecessary practice of silently skipping `replicaSet` if it's not a string.
* Fixes the format of `hosts_or_uri` passed to `MongoReplicaSetClient`
=> Fix connecting to MongoReplicaSetClient

mongoengine/common.py, mongoengine/queryset/transform.py, setup.cfg, tests/queryset/queryset.py
Currently doing a query like `BlogPost.objects(authors__in=author).count()`, where `author` is a single MongoEngine-`Document`, raises an obscure error:
```
raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: u'id' is not a valid ObjectId, it must
be a 12-byte input or a 24-character hex string
```
This pull requests adds a "sanity" check, and raises a TypeError explaining that you need to use an iterable with the `in`-operator.
The correct thing to do is: `BlogPost.objects(authors__in=[author]).count()`, but that's not obvious when you read the `ValidationError` shown above.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1237)
=> Raise TypeError when `__in`-operator used with a Document

CONTRIBUTING.rst
Python 2.6 is not supported anymore with version 0.11.0
=> Update CONTRIBUTING: Adapt supported interpreters

mongoengine/base/datastructures.py, tests/fields/fields.py
Fixes #1318 
The BaseList supported the __delitem__ operator in a manner
similar to DictList, however the key to a list is an index rather
than unique key. MongoDB does not support pulling from an array
by index; therefore the entire list must be marked as changed.
MongoDB reference: https://jira.mongodb.org/browse/SERVER-1014
=> Fixed ListField deletion bug. #1318

mongoengine/document.py, tests/document/instance.py
=> Raise an error when trying to save an abstract document

mongoengine/queryset/base.py, tests/queryset/field_list.py
Previously this would fail with `TypeError: unorderable types: int() < dict()` in Python 3.x
=> Fix BaseQuerySet.fields when mixing exclusion/inclusion with complex values

mongoengine/base/fields.py, tests/fields/fields.py
Fixes #1376 
Based on https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names.
=> Validate db_field

mongoengine/document.py
This is just a preparation for a bigger set of improvements to Document.save. It splits the huge unreadable method into a few logical sub-methods and adds some comments.
=> Cleaner Document.save

docs/guide/defining-documents.rst, docs/guide/signals.rst, mongoengine/fields.py
Removed obsolete documentation, ever since #105, the `post_delete`, `pre_delete` signals get triggered, even when `reverse_delete_rule` deletes records. Or am i missing something here?
There's even a test which tests exactly for this behaviour, which also was introduced in #105.
=> Fixed docs regarding reverse_delete_rule and delete signals

mongoengine/queryset/base.py, mongoengine/queryset/queryset.py, tests/queryset/queryset.py
Fixes #1469 #1475 and reverses an invalid "fix" from #1049 
Main changes:
* `BaseQuerySet.limit/skip/hint/batch_size` are now chained properly.
* `BaseQuerySet.order_by` now allows clearing a previously specified ordering (not just the default ordering as it used to).
* Public `BaseQuerySet.clone_into` method has been renamed to a private `_clone_into` (shouldn't have been public in the first place).
* `BaseQuerySet._get_order_by` method doesn't manipulate the cursor anymore (that was a poorly designed separation of concerns).
=> Fix cursor management

mongoengine/fields.py, tests/fields/fields.py
Prior to this PR, formatting the exception message would fail:
```
In [1]: from mongoengine.fields import URLField
In [2]: URLField().validate(u'http://привет.com')
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-2-023c2c193da6> in <module>()
----> 1 URLField().validate(u'http://привет.com')
/Users/wojcikstefan/Repos/temp/mongoengine/mongoengine/fields.py in validate(self, value)
145         # Then check full URL
146         if not self.url_regex.match(value):
--> 147             self.error('Invalid URL: {}'.format(value))
148             return
149
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-12: ordinal not in range(128)
```
=> Fix the exception message when validating unicode URLs

.gitignore, mongoengine/document.py, mongoengine/queryset/base.py, tests/document/indexes.py
The SAVE function of pymongo has been deprecated.
It does not raise an exception in case of duplication in value of _id, because in this case it treats the operation as UPDATE and not INSERT, and practically, does not do anything - not really duplicates the document, but also does not raise an exception
I stopped using SAVE and started using INSERT_ONCE instead, as recommended by pymongo
=> Issue #1472 - duplication in primary key (_id) raising an exception now

tests/fields/fields.py
@ephraimberkovitch fyi you pointed out in https://github.com/MongoEngine/mongoengine/pull/1485#discussion_r103173256 that many tests follow an invalid pattern. This PR is an attempt at cleaning some of it up. Feel free to submit similar patches for other parts of the codebase!
High level summary of the changes:
* Removed some redundant whitespace.
* Removed all redundant `drop_collection` calls (we only need those in the beginning of a test).
* Improved clarity of some docstrings.
* Tweaked some of the methods to test the same behavior in a more efficient manner.
* Minor PEP8 fixes.
* Break tests pertaining to the `CachedReferenceField` into a separate test class (makes the grouping cleaner and also prepares the code nicely before a larger inspection - many users have complained that the …
=> Clean up field unit tests

mongoengine/fields.py, tests/fields/fields.py
This is a replacement for https://github.com/MongoEngine/mongoengine/pull/1195
The original PR was created against master on our fork for some reason, this one is on a branch. I couldn't see any way to switch the branch the PR referred to.
I've also included another test to check dereferencing.
Sorry for the delay on this one @wojcikstefan
=> Allow ReferenceFields to take ObjectIds

mongoengine/fields.py, tests/document/instance.py, tests/fields/fields.py
Fixes #1228
Previously, email addresses containing unicode characters didn't work at all. Now, unicode domains are supported out of the box and utf8 validation on the user parts can be explicitly enabled. This PR also adds validation of IP-based domain parts (e.g. "user@[127.0.0.1]") and introduces support for whitelisting otherwise invalid domains (e.g. "root@localhost").
Support for unicode usernames is still somewhat limited in many packages, so that option should be enabled only after a thorough inspection of the other parts of the system. The domain whitelist is empty and the IP validation is disabled by default primarily to be consistent with the past behavior, and because many applications may choose to reject such addresses.
TL;DR validation of regular ascii-only email addresses …
=> Unicode support in EmailField

mongoengine/base/document.py, mongoengine/document.py, tests/document/instance.py
Fixes #1526, read https://github.com/MongoEngine/mongoengine/issues/1526#issuecomment-294385510 for the rationale.
=> Make EmbeddedDocument not hashable by default

mongoengine/base/fields.py, tests/document/instance.py
Building on top of #1448, we should also disallow explicit `db_field` values that aren't strings.
=> Better db_field validation

mongoengine/queryset/base.py, tests/queryset/queryset.py
Fixes #563 and closes #1002.
This PR introduces tweaks to `QuerySet.as_pymongo` - a method that hasn't been touched in at least a couple years. Part of me wants to get rid of it entirely and suggest that people use `Doc._get_collection().find(...)` if they need raw PyMongo documents, but perhaps that's too drastic of a change (and can be revisited when we make `_get_collection` public, see #1182).
This PR significantly simplifies the code and gets rid of an arguably useless `coerce_types` kwarg (the idea of converting values to MongoEngine-specific types in a method that's supposed to return raw PyMongo documents confuses me greatly). For now I also followed the previous logic of excluding `_cls` as an implementation detail and also excluding `_id` if it was only fetched for internal …
=> Cleaner as_pymongo

mongoengine/fields.py, tests/fields/fields.py
This happens in python 2.7 because `dateutil.parser.parse('')`
return `datetime.date.today()`
=> Fix empty string casted to datetime today in DateTimeField

mongoengine/queryset/base.py, tests/queryset/field_list.py
=> to_db_fields fix

.install_mongodb_on_travis.sh, .travis.yml, tests/queryset/geo.py
added test for #1311. tests working fine in current master, but not in <0.13
=> added as_pymongo test for PointField #1311

docs/changelog.rst, mongoengine/base/__init__.py, mongoengine/base/datastructures.py, mongoengine/fields.py, tests/fields/fields.py
Replacement for `ReferencField` and `GenericReferencField` which address issues from #1230 
The `passthrough` argument allows to use them as an *almost)* dropin replacement on existing codebase ;-)
=> Add LazyReferenceField & GenericLazyReferencField

docs/changelog.rst, mongoengine/connection.py
This is done to make it compatible with the connect function, and fixes issue #606.
=> Add db parameter to register_connection

mongoengine/document.py
I submitted PR for Document.modify fails on sharded collection. However, I don't know how to write unit test for it. Gladly, I checked it with manual
Created sharded cluster with 
<pre>
mlaunch --single --sharded 3
</pre>
<pre>
use test-db
db.doc.createIndex({name:1})
use admin
sh.enableSharding('test-db')
db.runCommand({shardCollection: "test-db.doc", key: {name:1}}
</pre>
and tried code snippet from #1569 .
=> Fix Document.modify fail on sharded collection #1569

docs/tutorial.rst
In other places, it says "MongoDB" but in Posts says "mongoDB"
=> fix case consistent mongoDB => MongoDB

AUTHORS, mongoengine/queryset/transform.py, tests/document/instance.py, tests/queryset/transform.py
Value should be treated as list-like (iterable) when `pull` is used with `in` #1654
=> Fix pull+in update queries

docs/guide/defining-documents.rst
MongoDB wants dates stored in UTC, but the functions used in this documentation to generate datetime objects would use server's local timezone - fix it!
=> MongoDB wants datetimes stored in UTC, but the functions used in this doc use local time

mongoengine/base/datastructures.py
A simple doc update to prevent some confusion regarding the EmbeddedDocumentListField's `update` method.
Source issue: #1726
=> Edit EmbeddedDocumentListField update() doc

mongoengine/queryset/base.py
The documentation for the `full_result`-argument to `queryset.update()` can be read as returning the updated documents/objects, whereas it's really returning just the full "PyMongo result dictionary".
This commit adds some wording and an example dictionary, to make it clear what the behavior is.
Basically the docs for `full_result` can be misread as having the same behavior as the `load_bulk`-argument to `insert()`.
=> queryset.update: `full_result`-argument not clearly described

mongoengine/queryset/base.py
I made a mistake in the merged PR #1762. As it just docs, it's not the worst, the formatting is just off because my brain was in Markdown-mode not RestructuredText-mode.
Single backticks should be double backticks.
I also removed the superfluous `u`-markers for unicode strings. They're in the output from Python, but they really just add noise (they're not important in terms of getting the point across).
=> Docs, queryset.update(): Fix backtick mistake

docs/apireference.rst, docs/guide/defining-documents.rst, mongoengine/fields.py
Documentation contained references to `LazyReference` and `GenericLazyReference` field types but  no documentation for these fields (how to use primary key and how to manually dereference).
Added documentation based on [this comment](https://github.com/MongoEngine/mongoengine/issues/1230#issuecomment-324673982) on PR #1230.
=> Add documentation for LazyReference and GenericLazyReference fields.

mongoengine/queryset/transform.py, tests/queryset/transform.py
Related Issue: #1729 
I have removed the usage of '$pushAll' from the `transform.update` function. This method has been deprecated since MongoDB v2.4. In its favor, I have implemented the preferred method of pushing multiples: [$each](https://docs.mongodb.com/v3.2/reference/operator/update/each/#up._S_each).
This will not make any change to mongoengine's api. Users will still be able to call `push_all` as an atomic update modifier. That being said, we should consider removing this verbiage in favor of `push_each`; this would be more consistent/clear with the operation that is being performed.
=> Removing the usage of the '$pushAll' operator

mongoengine/queryset/transform.py, tests/queryset/transform.py
Updated mongoengine.queryset.transform.update method to handle EmbeddedDocuementListField during pull operations in DB using mongoegning ORM
fixed : .udpate(pull__emb_doc__emb_doc_list=doc)
=> fixed : `pull` not working for EmbeddedDocumentListField, only working for ListFields #1534

docs/guide/text-indexes.rst
The search statement under the `Ordering by text score` section uses `search` on the QuerySet object instead of `search_text` and thus raised an `AttributeError`
AttributeError: 'QuerySet' object has no attribute 'search'
=> Updated text-indexes.rst

mongoengine/queryset/queryset.py
There's no need to explicitly raise StopIteration as that's what a bare return statement does for a generator function - so yes they're the same.
As of late 2014 return is correct and raise StopIteration for ending a generator is on a depreciation schedule. See PEP 479 for full details.
https://stackoverflow.com/q/14183803/248296
https://www.python.org/dev/peps/pep-0479/
=> Fixes #1641

mongoengine/context_managers.py, mongoengine/queryset/base.py, tests/queryset/queryset.py
Related Issue: #1491 
I have replaced our usage of PyMongo's `update` method with `update_one` and `update_many`. These new methods return an `UpdateResult` object -- the tests and code have been updated accordingly to handle this new object.
In order to accomplish this, I had to develop a new way of setting the write concern on the collection. This logic has been moved into `context_manager.set_write_concern`. This method will return a clone of the collection that is passed in and combine the previous write concerns with the new ones passed in.
=> removed deprecated warning for 'update' method

docs/guide/defining-documents.rst
This adds a snippet to describe the `auto_create_index` attribute in the Indexing section of the User Guide. It was confusing to me that this was only mentioned in the docstring of the `Document` object (http://docs.mongoengine.org/apireference.html#documents) so it's visible in the API section of the docs but not mentioned at all in the User Guide.
I also change the ordering of the attributes in the dictionary to match the ordering of their descriptions.
=> Add documentation for auto_create_index to the Indexing section of the Docs

mongoengine/dereference.py
Found that DeReference._attach_objects does not restrict the type of the v in the items,
but assumes that v.collection exists when v.id exists.
The results in some issue when I intended to use python-social-auth + social-app-flask-mongoengine.
(some weird thing happened in /disconnection)
I would like to add defensive programming for v as DBRef as illustrated in the pr.
=> defensive programming for v as an instance of DBRef in dereference.

mongoengine/document.py
=> Fix a typo

docs/changelog.rst, mongoengine/fields.py, tests/fields/fields.py
=> Date field

CONTRIBUTING.rst
Clarify in the doc that:
- python 2 should be used for developing on mongoengine
- the compatibility with python3 relies on the 2to3 package
(related to #1837)
=> Contributing doc update - Clarify python 2 should be used to develop on mongoengine

docs/guide/signals.rst
Since there is a .save() method on EmbeddedDocument, you could be tempted to attach a pre_save signal to an EmbeddedDocument (#1720). This update is an attempt to make this clearer.
=> Update signals doc - clarification on EmbeddedDocument

docs/guide/gridfs.rst, mongoengine/fields.py, tests/fields/file_tests.py
I believe the implementation is consistent but as mentioned in #710, it is unclear that you should save the Document hosting the GridFSProxy after calling .delete() or .replace() on the GridFSProxy.
=> Update gridfs.rst - make it clear that user must call Document.save()

mongoengine/base/document.py, mongoengine/document.py
While checking something else I've noticed the following dead code:
1)
```
if self._dynamic:        #  <--
dynamic_data = {}
for key, value in values.iteritems():
if key in self._fields or key == '_id':
setattr(self, key, value)
elif self._dynamic:        #  <-- useless
dynamic_data[key] = value
```
2)
```
__auto_convert = values.pop('__auto_convert', True)    # <-- pops '__auto_convert' from values
... (more code)
if self._dynamic:
...
else:
FileField = _import_class('FileField')
for key, value in values.iteritems():
if key == '__auto_convert':                                   # still checks if '__auto_convert' is there
continue
key = self._reverse_db_field_map.get(key, key)
if key in self._fields or key in ('id', 'pk', '_cls'):
if __auto_convert and value is not None:
field = …
```
=> remove dead code

mongoengine/dereference.py, tests/document/instance.py
Relates to #1688 
A lot of things are happening when calling hasattr(collection, 'objects'), and since hasattr swallows any exception under python2, it could hide nasty things, including index creation errors
=> Fix index creation error that was swallowed by hasattr under python2

mongoengine/base/utils.py, mongoengine/common.py, mongoengine/fields.py, mongoengine/python_support.py, tests/test_utils.py
Use a descriptor to lazily evaluates re.compile of the tough regexes in fields.py, especially the regex's from EmailField. It greatly reduces the import time of mongoengine (thus the startup time of application) so I think it is valuable
Let me know what you think of the descriptor implementation. An alternative is django's implementation of _lazy_re_compile (https://github.com/django/django/blob/11b8c30b9e02ef6ecb996ad3280979dfeab700fa/django/core/validators.py#L163) but it is quite heavy so I'm not sure you want to do this...
Related issue : #1806
=> Implemented lazy regex compiling for issue #1806

mongoengine/fields.py
I've seen so many people doing mistakes (including myself) when defaulting a DateTimeField to utcnow (using datetime.utcnow() instead of datetime.utcnow) that I believe its worth mentioning it explicitly in the doc.
Fixes #1583
=> minor improvement to DateTimeField doc

mongoengine/base/datastructures.py
Fixes #1664
Improve doc of EmbeddedDocumentList.filter and clarify that that it does not supports fancy operators like queryset.filter
=> Improve doc of EmbeddedDocumentList.filter, 

docs/guide/document-instances.rst
Make comment in validation/cleaning example more readable for those reading it for the first time.
=> Clarify comment in validation example

mongoengine/context_managers.py, tests/test_context_managers.py
Fixes #1865
- Fixed __exit__ of no_subclasses context manager so that it won't swallow errors
- repair the feature because it was completely broken since at least 0.10.0...
=> Fixes 2 bugs in no_subclasses context mgr

mongoengine/fields.py, mongoengine/queryset/transform.py, tests/queryset/queryset.py
Fixes inc/dec operators when using DecimalField + improve the doc and emphasize important problems of the DecimalField as it is implemented (#637)
Fixes #1517 
Fixes #1320
=> fix inc/dec operator with DecimalField + improve its doc

mongoengine/queryset/transform.py, tests/queryset/queryset.py
This is a clone of PR #1810 (which integrates #1766 fixes), since CI failed in there, I'm pushing this in order to have it integrated faster
Fixes #1286 
Fixes #844
=> CLONE - When building a query set from filters that reference the same field several times, do not assume each value is a dict

mongoengine/queryset/transform.py, tests/queryset/queryset.py
Fix issues #1286 and #844 (basically the same issue).
=> When building a query set from filters that reference the same field several times, do not assume each value is a dict

mongoengine/fields.py
The previous example of creating bi-directional delete rules was vague since the example defined only one class and the relationship between "Foo" and "Bar" wasn't clear. I added a more explicit example where the relationship between the two classes is explicit.
=> docs: use explicit register_delete_rule example

mongoengine/base/fields.py, mongoengine/fields.py, tests/fields/fields.py
Fixes #1368
The default value was weirdly handled and was defaulting to the current datetime automatically which is not logical because it isn't aligned with DateTimeField
=> Fix ComplexDateTime default value

mongoengine/fields.py, tests/queryset/queryset.py
The `basecls` attribute that can be given to the DictField constructor isn't doing anything, additionally it is also not documented and confusing with the `field` attribute
=> Remove DictField.basecls related code, it is useless

docs/guide/defining-documents.rst
The previous link goes to a page without the options mentioned.
=> Update link to index options

tests/document/class_methods.py, tests/document/delta.py, tests/document/dynamic.py, tests/document/indexes.py, tests/document/inheritance.py, tests/document/instance.py, tests/document/validation.py, tests/fields/fields.py, tests/fields/file_tests.py, tests/fields/geo.py, tests/queryset/field_list.py, tests/queryset/geo.py, tests/queryset/queryset.py, tests/queryset/transform.py, tests/queryset/visitor.py, tests/test_connection.py, tests/test_context_managers.py, tests/test_dereference.py
I noticed that there were many occurrences of poor assertions like
assertTrue(isinstance(a, b)) --> Should be assertIsInstance
assertTrue(a==b) --> assertEqual
assertTrue(a!=b) --> assertNotEq
assertTrue(a in b)  --> assertIn
It won't make a difference as long as the test passes but as soon as one will fail it would print more valuable info than just "Assert False"
I would also suggest to switch the whole suite to pytest but that's another story :)
=> Refactored some poor assertions across test suite

mongoengine/base/document.py
join expect strings, but if we use django ugettext_lazy like this:
```
choices=[(1, _("One")), (2, _("Two"))]
```
there will be `TypeError: sequence item 0: expected string, __proxy__ found`
this commif fixes error by converting label to string
=> fixed TypeError on translated choices

mongoengine/base/document.py, mongoengine/base/fields.py, mongoengine/fields.py, tests/queryset/queryset.py
The queryset.no_dereference() method was having side effect on the class Field (descriptor) _auto_dereference attribute. Meaning that existing instances could be impacted by a call to no_dereference and suddenly stop dereferencing. See below:
```
class User(me.Document):
name = me.StringField()
class Organization(me.Document):
name = me.StringField()
user = me.ReferenceField(User)
user = User(name='John').save()
Organization(name='GitHub', user=user).save()
org = Organization.objects.first()   # fetch an instance before the no_dereference call
_ = Organization.objects.no_dereference().first() # alters the _auto_dereference of the class field (i.e the ReferenceField descriptor) 
print org.user    # DBRef('user', ObjectId('5b9ec11d4ec5dc58df8290ba')) <-- SHould have been dereferenced
``` …
=> fix side effect from queryset.no_dereference

mongoengine/base/fields.py, tests/fields/fields.py
Detect when EmbeddedDocumentListField receives an EmbeddedDocument instance instead of a list. It is a common mistake and the previous error wasn't meaningful (was fired from _from_son). The same applies for DictField.
Fixes #1464
=> Handles edge case when EmbeddedDocumentListField receives a Document and not a list

mongoengine/fields.py, tests/queryset/queryset.py
Similarly to how #1892 fixed the issue for ReferenceField, this PR fixes the issue for GenericReferenceField that is suffering from the exact same issue. See below:
```
class Organization(me.Document):
name = me.StringField()
class User(me.Document):
name = me.StringField()
organization = me.GenericReferenceField()
organization = Organization(name='Github').save()
User(name='John', organization=organization).save()
user = User.objects.first()   # fetch an instance before the no_dereference call
user_no_derf = User.objects.no_dereference().first() # alters the _auto_dereference of the class field (i.e the ReferenceField descriptor) 
print(user_no_derf.organization)    # {'_cls': 'Organization', '_ref': DBRef('organization', ObjectId('5baaa27e4ec5dc49f0ffc86a'))} (This is fine) …
```
=> Fix side effect of no_dereference on GenericReferenceField

.install_mongodb_on_travis.sh, .travis.yml, README.rst, mongoengine/context_managers.py, tests/document/indexes.py, tests/queryset/queryset.py, tests/test_context_managers.py, tests/utils.py
Replaced MongoDB 2.4 tests in CI by MongoDB 3.2
Relates to #1445
=> Fixed tests to allow support of MongoDB 3.2 + Drop Mongo2.4 from CI

mongoengine/fields.py
Using QuerySet directly would fail if QuerySetNoCache was used. Sadly the
test suite does not have a case where QuerySet would appear here, so adding
a test for this special case is not trivial.
=> Fix invalid isinstance check in ListField.validate

.install_mongodb_on_travis.sh, .travis.yml, mongoengine/queryset/visitor.py, tests/document/class_methods.py, tests/document/indexes.py, tests/document/instance.py, tests/queryset/geo.py, tests/queryset/modify.py, tests/queryset/queryset.py, tests/utils.py
- renamed decorator "needs_mongodb_26" from test suite to "requires_mongodb_gte_26", so that it is clear that the test applies to >= 2.6
- removed reference to mongodb 2.4 in travis since it was removed recently
=> minor rework in test

mongoengine/document.py
Small fix to ensure to use the right document after pre_save_post_validation hook, which might modify the document itself (e.g., for adding an etag, which needs the final document for saving).
=> Bug fix: pre_save_post_validation could, in principle, modify the document

mongoengine/base/metaclasses.py, tests/document/inheritance.py
As suggested by wojcikstefan in https://github.com/MongoEngine/mongoengine/issues/1563#issuecomment-309483935, I've udpated the error message that gets thrown when you subclass a Document without setting allow_inheritance: True
=> Improve the error message that mentions that Document cant be subclassed

mongoengine/fields.py, tests/document/inheritance.py
Fixes a bug that occurs when referencing an abstract class in a ReferenceField (Fixes #1920) 
I believe this also fixes #1272, fixes #997
=> Fix a bug when using a ReferenceField(AbstractClass)

docs/guide/defining-documents.rst
Document the collation index option and the fact that additional options gets forwarded to pymongo's create_index method
Fixes #1929
=> Improve documentation for additional index options

mongoengine/fields.py, tests/fields/fields.py
Fixes #273 
If we give unicode instead of bytes to the BinaryField, it was passing the BinaryField.validate() but was failing during the .to_mongo() since bson.Binary fails if you give it a unicode
=> fix validator of BinaryField

mongoengine/base/document.py, tests/document/instance.py, tests/test_dereference.py
Fixes #1768, Fixes #1685
The initial code that was collecting the inspected id's in _get_changed_fields() was there to avoid infinite loop when a Document had a reference to himself in its Document but this is already handled by the
```if isinstance(field, ReferenceField)```
That got introduced later on, thus that code wasn't necessary anymore
=> Fix bug where an EmbeddedDocument with the same id as its parent would not be tracked for changes

docs/changelog.rst, mongoengine/document.py
=> Use insert_one instead of deprecated one #1899

docs/changelog.rst, mongoengine/base/document.py, tests/fields/fields.py
Fixes #1733 + clean code that is not necessary anymore
Closes #1743
=> Fix bug in _delta method - setting ListField to empty in DynamicDocument is faulty

docs/changelog.rst, mongoengine/base/document.py, tests/document/inheritance.py
Fixes #1950 
I actually introduced this in https://github.com/MongoEngine/mongoengine/commit/adfb039ba636202ce034e6104dc27f5bf74601c3#diff-e3e316e6686a3db66d2e679634f57f7f. I guess that was a mistake, my bad...
@erdenezul I think we should release a 0.16.1 with this, what do you think?
=> Regression bug fix - _cls not set in constructor

docs/changelog.rst, mongoengine/document.py, tests/queryset/queryset.py
Fixes #1958 
@erdenezul Please have a look when you have a chance as I think we need to move quickly on this before other people hit the bug. I guess we'll trigger a 0.16.2 when it get merged
Please also note that using mutable value for function param should be avoided ([see this post](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)) as it can lead to strange behavior. This is not the root cause of this bug though but better to fix this
=> Fix but with save(write_concern=None) - introduced in 0.16.1

AUTHORS, docs/changelog.rst, mongoengine/queryset/transform.py, tests/document/instance.py
$position and $push operators do not work with list in an EmbeddedDocument. Set key value to joined parts excluding the index at the end. Added test case
=> Fix bug #1965 of $position and $push operators do not work with nested list

mongoengine/base/document.py, mongoengine/dereference.py, tests/fields/fields.py
Using `DictField(ListField(ReferenceField(dbref=False)))` throws an error when accessing this attribute
Fixes #1453
=> Fix complex combinations of DictField(ListField(ReferenceField))

mongoengine/queryset/base.py
Current doc of .all() is a bit confusing as it sounds like it return a list (i.o a queryset)
Fixes #1977
=> minor update to .all() doc to make it clear that it return a queryset

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/queryset.py
Closes https://github.com/MongoEngine/mongoengine/issues/1973 and should align the logic to work the same as in pymongo when using as_pymongo
=> Bring back _cls and _id fields just as they return in pymongo

mongoengine/document.py, tests/document/dynamic.py
The restriction on fields that can't start with underscore only seem to apply to undeclared fields.
Fixes #1994
=> Improve DynamicDocument documentation regarding fields with underscore

docs/changelog.rst, mongoengine/document.py, tests/document/instance.py
Relates to  #1570 
I also deprecate .reload because just like .save, I believe it confuses users to see that on the EmbeddedDocument
=> Add DeprecationWarning for EmbeddedDocument.save & .reload

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/queryset.py
Fix documentation of what's returned by Queryset.update when full_result=True is provided
Document the breaking change that was introduced in 0.15.3 and not reported 
Fixes #1995
=> Fix documentation of Queryset.update regarding full_result #1995

.install_mongodb_on_travis.sh, .travis.yml, README.rst, docs/changelog.rst, mongoengine/document.py, mongoengine/mongodb_support.py, tests/document/indexes.py, tests/fields/fields.py, tests/queryset/queryset.py, tests/utils.py
Adds Mongo34 to travis and fix the tests to support this
Mongo 3.2, which is the latest version we officially support (and run our test suite against) reached end of life in 2018 so it is time to officially support 3.4 :)
Relates to #1727 and #1445
=> Add support for Mongodb 34 (tests/travis)

mongoengine/connection.py, mongoengine/context_managers.py, mongoengine/document.py, mongoengine/pymongo_support.py, mongoengine/python_support.py, mongoengine/queryset/base.py, mongoengine/queryset/transform.py, tests/document/class_methods.py, tests/document/delta.py, tests/document/inheritance.py, tests/document/instance.py, tests/fields/file_tests.py, tests/queryset/queryset.py, tests/test_connection.py, tests/test_context_managers.py, tests/test_replicaset_connection.py, tests/utils.py
rework the tests to avoid deprecation warnings from pymongo
- remove/count/add_user/insert
- added pymongo_support
Relates to #1491
=> refactored deprecated pymongo methods in tests

AUTHORS, docs/changelog.rst, mongoengine/base/document.py, tests/document/indexes.py
Solves issue #2020, it allows setting unique index for both `SortedListField` and `EmbeddedDocumentListField`.
=> Generate Unique Indices for SortedListField and EmbeddedDocumentListField

README.rst, docs/changelog.rst, mongoengine/document.py, requirements.txt, setup.py, tests/document/indexes.py, tests/document/json_serialisation.py, tests/queryset/queryset.py, tests/test_connection.py
Closes #2017
As spotted in the linked issue, we aren't pymongo < 3 compatible since some time. We could simply bump the required pymongo version to >=3.0 but I thought that we could push it further and require pymongo>=3.5 as:
- its the oldest version against which we run the test suite in travis
- recent version of pymongo are fully backward compatible
Let me know what you think @erdenezul, if you prefer that I get back to >=3.0, I'll revert some changes
=> Bump the required version of pymongo to >=3.5

AUTHORS, docs/changelog.rst, mongoengine/base/fields.py, tests/test_dereference.py
G'day! 
Thank you for this amazing library! I came across a peculiar behaviour when working with a particular edge case which I'm unsure is a bug or the intended behaviour. 
I have a document with a `ListField` of `GenericLazyReferenceField` instances. Something like: 
```python
class Entity(mongoengine.Document):
related_to = fields.ListField(fields.GenericLazyReferenceField())
```
If there are references to documents within `Entity.related_to` which have been deleted or cannot be found in the database, each call to `Entity.related_to` will continue to query the database to try and dereference the values. 
For example, if I have an Entity `name="my-entity"` with the following data: 
```
[{'_cls': 'Entity',
'_ref': DBRef('entities', ObjectId('5c402bb418a6893bd36f5e30'))}]
```
and this …
=> Fix Multiple Redundant Dereference Calls

AUTHORS, docs/changelog.rst, mongoengine/connection.py, tests/test_connection.py
So, the issue is that if you specify db name incorrectly, mongoengine doesn't fail immediately, instead it fails upon your first attempt to store/read anything. Which is not obvious and could create some impression that there is something wrong with the document, because saving the document failed in the first place, not connecting to the db itself.
Other people were confused by this before me: https://github.com/MongoEngine/mongoengine/issues/1718
=> Fail fast when db name is invalid

docs/changelog.rst, docs/guide/connecting.rst, mongoengine/base/common.py, mongoengine/connection.py, mongoengine/document.py, tests/test_connection.py, tests/test_context_managers.py, tests/utils.py
Refactoring around connect/disconnect as it used to have some serious issue
- expose `mongoengine.connection.disconnect` and `mongoengine.connection.disconnect_all`
- Fix disconnect function #566 #1599 #605 #607 #1213 #565
- Improve connect/disconnect documentations
- POTENTIAL BREAKING CHANGES: (associated with connect/disconnect fixes)
- calling `connect` 2 times with the same alias and different parameter will raise an error (should call disconnect first)
- disconnect now clears `mongoengine.connection._connection_settings`
- disconnect now clears the cached attribute `Document._collection`
This Fixes #566, Fixes #1599, Fixes #605, Fixes #607, Fixes #1213, Fixes #565, Fixes #2010
=> Fix connect/disconnect functions

docs/changelog.rst, mongoengine/fields.py, tests/fields/fields.py, tests/fields/test_embedded_document_field.py
Fix an existing bug when querying fields of subclasses of EmbeddedDoc
+ moved test related to EmbeddedDocumentField into its own module
Closes #1961, Closes #1492, Closes #475
=> Fix querying embeddedDoc sub classes

docs/changelog.rst, mongoengine/document.py
Fixes #568 
Unfortunately I didn't find a great way to test this, I could do something with `mock` though, let me know if you want me to go that way
=> Fix default write concern on save call that was overwriting connection WC

mongoengine/queryset/transform.py, tests/queryset/queryset.py, tests/queryset/transform.py
Consider the following model:
```python
class Word(EmbeddedDocument):
word = StringField()
index = IntField()
class SubDoc(EmbeddedDocument):
heading = ListField(StringField())
text = EmbeddedDocumentListField(Word)
class MainDoc(Document):
title = StringField()
content = EmbeddedDocumentField(SubDoc)
```
If we want to remove all the `Word` list entries in all `MainDoc` records which contain a list of words, you can use:
```
MainDoc.objects().update(pull__content__text__word__in=['foo','bar'])
```
However, right now it is not possible to use the `nin` operator in this context, to remove the entries that do not contain certain words as in:
```
MainDoc.objects().update(pull__content__text__word__nin=['foo','bar'])
```
This PR add support for `nin` operator with a `pull` update.
=> Add support for '$nin' when transforming a 'pull' update query.

mongoengine/document.py
* Edited the _save_update method to use update_one instead of update, see [Deprication Warnings with pymongo 3.7.1](https://github.com/MongoEngine/mongoengine/issues/1899).
=> Use update_one instead of deprecated update #1899

.travis.yml, README.rst, mongoengine/connection.py, mongoengine/mongodb_support.py, requirements.txt, setup.py, tests/document/class_methods.py, tests/document/indexes.py, tests/document/instance.py, tests/queryset/geo.py, tests/queryset/modify.py, tests/queryset/queryset.py, tests/utils.py, tox.ini
Previously, we were running the test suite for several combinations of MongoDB, Python, and PyMongo:
- PyPy, MongoDB v2.6, PyMongo v3.x (which really means v3.6.1 at the moment)
- Python v2.7, MongoDB v2.6, PyMongo v3.x
- Python v3.5, MongoDB v2.6, PyMongo v3.x
- Python v3.6, MongoDB v2.6, PyMongo v3.x
- Python v2.7, MongoDB v3.0, PyMongo v3.5.0
- Python v3.6, MongoDB v3.0, PyMongo v3.5.0
- Python v3.5, MongoDB v3.2, PyMongo v3.x
- Python v3.6, MongoDB v3.2, PyMongo v3.x
- Python v3.6, MongoDB v3.4, PyMongo v3.x
- Python v3.6, MongoDB v3.6, PyMongo v3.x
There were a couple issues with this setup:
1. MongoDB v2.6 – v3.2 have reached their End of Life already (v2.6 almost 3 years ago!). See the "MongoDB Server" section on https://www.mongodb.com/support-policy.
2. We were only testing two …
=> Update the test matrix to reflect what's supported in 2019

docs/changelog.rst, mongoengine/base/fields.py, mongoengine/errors.py, tests/fields/fields.py
While checking the coverage, I noticed that the custom `validation` callable that we can give to the field constructor had no test coverage.
I took the opportunity to change the way the callable is expected to work, the callable is now expected to raise a ValidationError (and no onger expect a `False` return) when validation fails. This is a BREAKING CHANGE but IMO it is better as:
- more intuitive and closer to django's implementation
- it allows the user to customize the error message
User that miss the breaking change should notice it very quickly due to the DeprecatedError that is being raised in case they didnt update their `validation` method (cfr diff)
=> custom field validator is now expected to raise a ValidationError

docs/changelog.rst, mongoengine/base/document.py, mongoengine/document.py, tests/document/instance.py, tests/test_signals.py
Document.save is currently making 2 calls to to_mongo (before and after validation), this is expensive  when objects are very large. Since the first call was only used to identify if the document is created or updated, we could restrict the call with to_mongo(fields=['id'])
=> Improve perf of Document.save

docs/changelog.rst, mongoengine/connection.py, tests/test_connection.py
Fix issue when using multiple connections to the same mongo instance using different credentials
Fixes #2047
=> Fix connection issue when using different authentication in different dbs

docs/apireference.rst
Fix the fact that some important members (e.g: to_json, validate, clean, etc) of Document/EmbeddedDocument/etc classes aren't displayed in the Api reference doc because they are defined in the parent (BaseDocument)
This was noticed in #549
=> Add Document inherited members to docs

mongoengine/base/document.py
1. We were unnecessarily creating a `changed_fields` variable, assigning `[]` to it.
2. We were not modifying it at all.
3. In the end, we were setting `obj._changed_fields` to that variable instead of `[]` directly.
There's still more work to be done to make handling of `_changed_fields` simple and intuitive (see the TODO in the code), but this minor tweak will do for now.
=> Clean up how _changed_fields are set in BaseDocument._from_son

tests/document/instance.py
This PR splits up custom PK field tests. The new approach more closely aligns with the rule that a single tests should test one thing and one thing only. Previous code tested like 4 different things in a
single test and was hard to follow.
=> Custom ID field test improvements

docs/changelog.rst, mongoengine/__init__.py
Hi @wojcikstefan @erdenezul , 0.18.0 suffered from a bug (#2082) and we need to release a 0.18.1 asap.
The bug only affects models with custom primary keys, let me know if you have suggestion to this.
I checked the other commits that were merged since 0.18.0 and it mainly update to docs or tests so it should be safe to include them in 0.18.1
=> Bump version number and update changelog for 0.18.1

docs/guide/defining-documents.rst, mongoengine/document.py
This closes #2096.
Previous documentation of the `shard_key` meta attribute was missing the crucial point that it really only matters if your collection is sharded over a compound index.
=> Improve Document.meta.shard_key docs

mongoengine/fields.py, mongoengine/queryset/base.py, tests/queryset/queryset.py
Relates to #1491, its just a step forward but we still have some pymongo deprecated methods being called
=> remove pymongo deprecated methods: find_and_modify & remove

docs/changelog.rst, mongoengine/base/document.py, mongoengine/base/metaclasses.py, tests/document/instance.py, tests/fields/test_lazy_reference_field.py
For example, if you had the following class:
```py
class Person(Document):
name = StringField()
age = IntField()
```
You could instantiate an object of such class by doing one of the following:
1. `new_person = Person('Tom', 30)`
2. `new_person = Person('Tom', age=30)`
3. `new_person = Person(name='Tom', age=30)`
**From now on, only option (3) is allowed.**
Supporting positional arguments may sound like a reasonable idea in this heavily simplified example, but in real life it's almost never what you want (especially if you use inheritance in your document definitions) and it may lead to ugly bugs. We should not rely on the *order* of fields to match a given
value to a given name.
This also helps us simplify the code e.g. by dropping the confusing (and undocumented) …
=> Drop support for positional arguments when instantiating a document

tests/fields/fields.py
This is a follow-up after #2107.
Not sure what happened here, but in https://github.com/MongoEngine/mongoengine/pull/2107/commits/87194856ecc5076bec2a186bae60c5d5b25c01ed I committed a copy-paste of the same test instead of a test validating the `ListField.max_length` behavior along with a "set" operator 🤦‍♂ 
See https://github.com/MongoEngine/mongoengine/pull/2107#issuecomment-506353904 for context.
=> Fix the duplicate ListField max_length test

docs/changelog.rst, mongoengine/connection.py, tests/test_connection.py, tests/test_replicaset_connection.py
I originally changed the exception name from `ConnectionError` to `MongoEngineConnectionError` in
https://github.com/MongoEngine/mongoengine/pull/1428/commits/b02904ee750a30f8e2246a326376b40358543101, inspired by landscape.io's package health report, which argued that `ConnectionError` is already a [built-in exception in Python 3](https://docs.python.org/3/library/exceptions.html#ConnectionError).
I do agree that we shouldn't override built-in exceptions. [0] That said, it’s silly to add a "MongoEngine" prefix to any class within the `mongoengine` module (and *especially* to *just one* exception class out of many). I've decided to do [what PyMongo does](
https://github.com/mongodb/mongo-python-driver/blob/8855a510a80a30268ffd4b90be65fb26929648e2/pymongo/errors.py#L59) and call this …
=> Rename MongoEngineConnectionError to ConnectionFailure

docs/changelog.rst, mongoengine/queryset/base.py
This param has been deprecated for a while and indeed it's useless. You can very easily do:
```py
import pprint
(...)
plan = SomeDoc.objects(...).explain()
pprint.pformat(plan)
```
=> Drop the deprecated "format" param from BaseQuerySet.explain

mongoengine/connection.py
Put the documentation of the parameter 'name' of the function
'register_connection' in order of appearance in the function signature.
=> Document function parameters in correct order

docs/changelog.rst, mongoengine/base/document.py, mongoengine/document.py, tests/document/instance.py
Previous implementation of `Document._object_key` was *kinda* working on MongoEngine-level fields (e.g. using `pk` instead of `_id` and separating nested field parts by `__` instead of `.`), but then it was also attempting to transform field names from the `shard_key` into DB-level fields.
This, expectedly, didn't work well. Most of the test cases added in this commit were failing prior to the code fixes.
This fixes updating, modifying, deleting, and reloading documents that specify a shard key where at least one of its fields has a different representation in MongoEngine vs in the database (e.g. the PK or fields specifying a different `db_field`).
=> Fix Document._object_key

mongoengine/base/document.py, tests/document/instance.py
I'm still not a fan of this method for a bunch of reasons*, but at least it's easier to understand now.
\* For example, it accepts string data (most people likely dump their data just to make it a string OR even if they have string data, they could easily decode it into a dict outside of MongoEngine). Also its default `created` value might be confusing (I added a TODO about it in this PR).
=> Improve BaseDocument.from_json tests and documentation

mongoengine/connection.py, tests/test_connection.py
When passing host `mongomock://localhost/some-default-database` to `connect` the default database was `"test"` instead of `"some-default-database"`.
Fixes: #2130
=> Set default database when using mongomock.

mongoengine/queryset/base.py, tests/queryset/test_queryset.py
Previously this was always set for all requests. The parameter is only
documented as supported for certain queries, so this was probably wrong.
Mongo version 4.2 fails update queries that have this parameter set making
mongoengine unusable there. Fixes #2148.
=> Only set no_cursor_timeout when requested

docs/faq.rst, docs/index.rst
Added a FAQ to RTD and documented the fact that mongoengine is based on PyMongo and offers no support for async driver
Fixes #2155
=> Document no async driver support

tests/test_connection.py
fix MongoClient.database_names() -> .list_database_names()
and connect(..., j=1) --> connect(..., journal=1)
as they were raising deprecaiton warnings
=> fix 2 pymongo deprecation warnings

.travis.yml, README.rst, docs/changelog.rst, docs/conf.py, mongoengine/context_managers.py, mongoengine/queryset/base.py, setup.cfg, setup.py, tests/document/test_instance.py, tests/fields/test_complex_datetime_field.py, tests/fields/test_embedded_document_field.py, tests/fields/test_fields.py, tests/fields/test_reference_field.py, tests/test_ci.py, tests/test_common.py, tests/test_connection.py, tests/test_context_managers.py, tests/test_datastructures.py, tests/test_replicaset_connection.py, tests/test_utils.py, tests/utils.py, tox.ini
Relates to #2114 
This changes the runner for development and CI from nose to pytest, moving to pytest was a piece of cake but there were a few things that got in my way as I tried to maintain all existing behavior:
1) the fact that we used `python setup.py test` to run the tests **
2) the fact that we do a dryrun of tox in the `install` section before the actual run in the `script` section, this implies that we pass argument to `python setup.py test`. I'm not sure if this is a common thing but I like the idea to separate tox's venv setup from running the test suite
3) the fact that pytest runs the test against the repository code i.o of the built code, this clashed with 2to3 and required a custom `TestCommand` class in setup.py
4) some incompatibilities in the libraries:
4.1) pytest > 5 …
=> Switch to pytest as runner

setup.py
In `README.rst`, a version of `six` of at least `1.10.0` is specified. This was missing from the requirements, potentially leading to broken installations.
=> Specify version of requirement

docs/changelog.rst, mongoengine/base/document.py, tests/document/test_instance.py
Improve error message from InvalidDocumentError whenever an embedded document has a bad shape (e.g due to migration)
It will now mention the concerned field more explicitly and will also specify what type was found (i.o of the expected dict)
Fixes #2180
=> Improve error message from InvalidDocumentError

AUTHORS, docs/changelog.rst, mongoengine/fields.py, tests/document/test_instance.py
Previously, when reading a LazyReferenceField from the DB, it was stored internally in the parent document's _data field as an ObjectId. However, this meant that equality tests using an enclosing EmbeddedDocument would not return True when the EmbeddedDocument being compared to contained a DBRef or Document in _data. Enclosing Documents were largely unaffected because they look at the primary key for equality (which EmbeddedDocuments lack).
This makes the internal Python representation of a LazyReferenceField (before the LazyReference itself has been constructed) a DBRef, using code identical to ReferenceField.
Fixes #2181
=> Fix EmbeddedDocument equality with LazyReferenceFields

AUTHORS, mongoengine/fields.py, tests/fields/test_dict_field.py
Starting in MongoDB >= 3.6, it is valid for dictionary keys to have "$" or "." in them as long as they don't start with "$"
[Source](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names)
Relevant Issue: #1594 (Currently closed, but should be re-opened)
=> Add ability for dict keys to have "." or "$" in MongoDB >= 3.6

docs/changelog.rst, mongoengine/__init__.py, setup.py
I've seen in a recent PR that travis was failing with a SyntaxError in the Pillow library.
It turned out that Pillow did a recent release (7.0.0) and they dropped support for Python2 (which finally reached EOL). To avoid users from hitting this issue, let's limit the pillow release and release 0.19.1 asap.
=> Bump version to 0.19.1 + force pillow to be < 7.0.0

AUTHORS, mongoengine/document.py
In the documentation of the `save()` function, it is not clear that after execution the saved object (Document) will be returned.
=> Add return info in the save function docstring

docs/changelog.rst, mongoengine/queryset/transform.py, tests/queryset/test_transform.py
close MongoEngine/mongoengine#2263
=> Fix for combining raw and regular filters

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/test_queryset.py
Add support for the [$elemMatch](https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/) projection operator on querysets. It works the same way "slice" does. Take for instance the following document structure:
```python
class Bar(EmbeddedDocument):
v = StringField()
z = StringField()
class Foo(Document):
x = StringField()
y = IntField()
items = EmbeddedDocumentListField(Bar)
```
The following query
```
Foo.objects.fields(elemMatch__items={'z': 'some value'})
```
will return `Foo` objects where the `items` contain only the first Bar embedded document for which `z` is `"some value"`, otherwise, the field will contain an empty string. 
Closes #2268
=> Add support for the elemMatch projection operator

docs/changelog.rst, mongoengine/fields.py, mongoengine/mongodb_support.py, tests/fields/test_dict_field.py
Fixes #2239
I havn't found an easy way to get the mongodb version associated with the database (associated with the Document class) from the DictField and I don't think it's a good idea to try to do so.
So I've only kept the validation rule for the latest mongo (valif >=3.6)
=> Fix bug introduced in 0.19 related to DictField validation

mongoengine/base/datastructures.py
The docstring on EmbeddedDocumentList.create() is a bit confusing since, from my understanding, it does no saving to the db at all. It also seems to contradict itself. I corrected this and made the behavior description a bit more explicit.
=> Fix EmbeddedDocumentList docstring

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/test_queryset.py
The read_concern property was getting dropped during clone(), which is used by a lot of operations that would be affected by the read concern setting.
Also set the read_concern value on aggregate() calls.
Fixes: https://github.com/MongoEngine/mongoengine/issues/2332
=> Add read_concern to cloned properties. Add read_concern to aggregate().

mongoengine/document.py, mongoengine/fields.py, tests/queryset/test_transform.py
See the test for my failed scenario. It's reduced down from my original query a bit to focus on the culprit.
The query in the test would return something like:
```python
{'drinks': {'$all': [{}, {}]}}
```
Whereas it should really return what I asserted:
```python
{ 'drinks': {'$all': [{'$elemMatch': {'_id': 'drink_1'}, {'$elemMatch': {'_id': 'drink_1'}]}}
```
=> Fix query transformation regarding special operators

.readthedocs.yml, requirements.txt
Fixes #2395
Force it to use python 3.7 instead of the default 2.7
Python 3 is the default for readthedocs but since the project is old, it still defaults to 2.7 unless explicitly stated (through a .readthedocs.yml)
=> Fix readthedocs build that failed

AUTHORS, mongoengine/document.py, tests/document/test_instance.py
Fix for https://github.com/MongoEngine/mongoengine/issues/2154
Inside the function def `_save_update()`, we have the logic that adds the shard key to the query. This is not only needed for `update_one()` of the pymongo lib, but also for `find_one_and_replace()`, which is used in `_save_create()`.
Therefore it makes sense to strip this functionality out of `_save_update()` and use it as well in `_save_create()`, which is done in this PR.
=> Bugfix #2154

docs/changelog.rst, mongoengine/base/document.py, tests/document/test_dynamic.py
Fixes #2412
For some reason it was behaving differently for Document and DynamicDocument in the constructor
=> Bug fix in DynamicDocument which is not parsing known fields

README.rst
in order to emphasize that repo is using autoformatter black as it is often forgotten in PR and makes CI failing. It seems common to add it
=> Add black badge to readme

docs/changelog.rst, mongoengine/base/document.py, tests/document/test_instance.py, tests/fields/test_fields.py
Fix some issues related with db_field in constructor by removing fied/db_field translation that shouldn't occur in constructor
This fixes some (but not all) issues highlighted in #1741 (some test cases were ported)
=> Fix some issues related with db_field in constructor

mongoengine/fields.py, tests/fields/test_lazy_reference_field.py
See #2375 for details. Test included.
=> Fix LazyReferenceField dereferencing in embedded documents

setup.py, tests/fields/test_file_field.py
Restriction was added due to Py2 support that we dropped in 0.20.0
Fixes #2427
=> Remove restriction on Pillow version in tests

setup.py, tox.ini
The changelog for 0.22 indicates that Python 3.5 support was removed:
> Drop support for Python 3.5 by introducing f-strings in the codebase
The package should no longer declare that it supports 3.5
=> Drop Python 3.5 support

docs/guide/connecting.rst
connection example shows a password of 12345, but text spoke of qwerty
=> Fix inconsistency with example

docs/guide/defining-documents.rst, mongoengine/document.py
The doc currently mentions that we lower the class name, but we are actually snake_cas'ing it so it's imprecise
in response to 
https://stackoverflow.com/questions/66016012/mongoengine-collection-naming-with-uppercamelcase
=> Fix for imprecise doc on collection name (CamelCase -> snake_case)

mongoengine/base/fields.py, mongoengine/fields.py
As it is today, it's not easy to read a profiling output from MongoEngine snippet as _from_son is both used during lazy loading and for instantiating EmbeddedDocument.
The usual suspect when there are performance problem with MongoEngine is the N+1 query issue due to the lazy loading of reference field. This PR will provide an exact count of the lazy loaded attribute, allowing for a better profiling experience and hopefully  pinpoint the bottleneck in a clearer way
=> Add _lazy_load_ref methods to make profiling easier

docs/changelog.rst, mongoengine/fields.py, tests/fields/test_enum_field.py
The `mongoengine.fields.EnumField` has the current behavior : if `choices` parameter is specified it raises a `ValueError`. 
I would like to alter that behavior because it makes sens to want to restrict the field to a subset of the possible values of an enum. I enhanced the value check to raise on invalid `choices` values.
=> Fixing EnumField choices validation

mongoengine/document.py, tests/document/test_instance.py
=> Fix instance._qs that was failing due to bad parametrization that went unnoticed

mongoengine/errors.py
all engine exception extends the primitive **Exception** class.
it would be better to define a base exception class for Engine that can be wrapped:
```python
try:
except MongoEngineException as e:
```
in this way i can capture a base exception raised by the mongoengine module
=> define a base exception for engine

docs/guide/defining-documents.rst
Though hidden away in the generated [api reference](https://docs.mongoengine.org/apireference.html#mongoengine.DynamicEmbeddedDocument), DynamicEmbeddedDocument isn't mentioned at all in the usage sections, and web searches for terms like "dynamic embeddeddocument [mongoengine]"  bring up stackoverflow posts such as [this one](https://stackoverflow.com/questions/14400963/dynamic-embeddeddocument-with-mongodb-mongoengine) where the answer actually links to the dynamic documents section of the docs...but doesn't actually mention that DynamicEmbeddedDocument exists. This small change should hopefully improve discoverability.
=> Mention DynamicEmbeddedDocument in usage docs.

AUTHORS, docs/changelog.rst, mongoengine/document.py, tests/document/test_instance.py, tests/fields/test_embedded_document_field.py, tests/queryset/test_modify.py
This is based on #2495 , it's a slightly modified version
I decided to set `_instance` to None instead of its initial value because I don't see why we would want the deepcopy of an EmbeddedDoc to point to the initial parent Document and it may create some weird bugs.
I believe it's safer that the deepcopied instance isn't attached to any parent Document, like it is when it is instantiated
=> Fix embedded instance deepcopy

mongoengine/fields.py
fix decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>] error if DecimalField param precision is zero or less
=> fix DecimalField precision

docs/guide/defining-documents.rst, docs/guide/migration.rst, mongoengine/document.py
improve list_indexes, ensure_indexes docstring and add index migration example example
Fixes #2560
=> improve index doc 

AUTHORS, docs/guide/querying.rst, mongoengine/queryset/base.py, tests/queryset/test_queryset.py
Fix on top of https://github.com/MongoEngine/mongoengine/pull/2566
=> Idoshr master fixed

.github/workflows/github-actions.yml, docs/requirements.txt
As pointed here (https://github.com/MongoEngine/mongoengine/pull/2578#issuecomment-945092623) , there was a problem in the pymongo-mongodb versions matrix
=> fix compatibility issue in CI

mongoengine/document.py, tests/queryset/test_queryset.py
Prevent from overriding custom QuerySet by new default QuerySet.
```mongoengine.document.Document._qs(self)```
For example:
Post.objects.delete()
post.delete() 
Internally both methods should use the same QuerySet if custom class was configured.
=> Prevent override custom manager

.github/workflows/github-actions.yml, AUTHORS, docs/changelog.rst, mongoengine/base/document.py, mongoengine/connection.py, mongoengine/context_managers.py, mongoengine/document.py, mongoengine/pymongo_support.py, mongoengine/queryset/base.py, setup.py, tests/document/test_dynamic.py, tests/document/test_indexes.py, tests/document/test_inheritance.py, tests/document/test_instance.py, tests/queryset/test_geo.py, tests/test_connection.py, tests/test_context_managers.py, tox.ini
This change follows up on top of #2600 and includes the following updates:
- merge master
- fixes for `GEOHAYSTACK` removal
- fixes for `max_pool_size` move
- fixes for `map_reduce` and `inline_map_reduce` removals
- fixes for `eval` removal
- fall back to the `pythonLegacy` UUID encoding for compatability with pymongo 3.x.
- fixes for SON.keys() not returning a list
- fixes for removed `collection.update`
- bubble up operation failure if an unsupported document count is attempted (The user can fetch the documents with `len(list(queryset))` or modify the query as needed).
- fixes for `db.authenticate` removal
The test suite is now passing locally and I'm opening this up in the main repo to run against the CI. I had originally opened https://github.com/bagerard/mongoengine/pull/20 to …
=> pymongo 4.0 support

setup.py
I noticed this was missed in `0.24.0` as installing via `pip-tools` which is checking the version constraints.
=> update dependency specifier to allow pymongo 4.x

mongoengine/queryset/base.py
The current check in https://github.com/mongoengine/mongoengine/blob/master/mongoengine/queryset/base.py#L725 uses the deprecated `empty` property.
=> Don't use deprecated property for emptiness check

docs/upgrade.rst, tests/document/test_instance.py, tests/fields/test_fields.py, tests/fields/test_file_field.py, tests/queryset/test_geo.py
There are small typos in:
- docs/upgrade.rst
- tests/document/test_instance.py
- tests/fields/test_fields.py
- tests/fields/test_file_field.py
- tests/queryset/test_geo.py
Fixes:
- Should read `explicitly` rather than `explcitly`.
- Should read `document` rather than `docoument`.
- Should read `distance` rather than `distace`.
- Should read `dereferenced` rather than `derefenced`.
- Should read `aggregation` rather than `aggreation`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

mongoengine/queryset/base.py
distinct automatically dereferences the results, however it should obey the  `_auto_dereference`, set by `no_dereference()`. This change makes distinct query not to dereference the values when `no_dereference()` is called on the queryset
For example, suppose I have a collection of BlogPost documents, each of which has a `user` ReferenceField pointing to a User document.  If I'd like to count the number of unique users who've written blog posts, I could do the following:
len(documents.BlogPost.objects(query).no_dereference().distinct("user"))
In this case, dereferencing all of those `user` fields just slows down the query as distinct doesn't obey the `_auto_dereference` field value set by the `no_dereference()` method.
The changes in the PR check for `_auto_dereference` value before …
=> Turning off dereferencing for the results of distinct query.

docs/guide/defining-documents.rst
`db_field` allows you to use an alternative field for MongoDB operations
This allows you to use a different attribute than the name of the field
used in MongoDB.
resolves #2655
=> Add an example on how to use the db_field to the docs in 2.3.3.1

mongoengine/connection.py
This adds aws authentication to mongo engine
The 
```and ("authmechanismproperties" not in conn_settings.keys())``` 
line is added to stop the mongoengine from attempting to reconnect the database upon calling it the second time.
Closes #2507
=> Added aws authentication to mongo engine

.pre-commit-config.yaml
importlib_metadata 5.0 that introduced breaking changes (breaks on py 3.7)
flake8 was failing with
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
File "/home/bgerard/.cache/pre-commit/repope3a67k1/py_env-python3.7/bin/flake8", line 8, in <module>
sys.exit(main())
File "/home/bgerard/.cache/pre-commit/repope3a67k1/py_env-python3.7/lib/python3.7/site-packages/flake8/main/cli.py", line ...
File "/home/bgerard/.cache/pre-commit/repope3a67k1/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
```
=> Fix issue with flake8 and importlib_metadata 5.0

.github/workflows/github-actions.yml
Fix the fact that we can't run workflow manually on branches
=> allow_workflow_dispatch as trigger

benchmarks/test_basic_doc_ops.py, benchmarks/test_inserts.py, benchmarks/test_save_with_indexes.py, docs/changelog.rst, docs/guide/defining-documents.rst, mongoengine/document.py, tests/document/test_indexes.py, tests/utils.py
Fixing conflict on top of  https://github.com/MongoEngine/mongoengine/pull/2702
=> [Clone] Breaking change: Improve save() performance by skipping index creation

benchmarks/test_basic_doc_ops.py, benchmarks/test_inserts.py, benchmarks/test_save_with_indexes.py, docs/changelog.rst, docs/guide/defining-documents.rst, mongoengine/document.py, tests/document/test_indexes.py
Indexes are now only created when a Model is first used, eg the first call to save() or on the first call to _get_collection(), or when the new meta["auto_create_index_on_save"] option is set to True. This is a minor breaking change for some applications. As a workaround apps can explicitly call ensure_indexes() or set meta["auto_create_index_on_save"] to True. 
Note that with the default settings (auto_create_index=True + auto_create_index_on_save=False) indexes are still created after on a Document's first use, or first use after Document.drop_collection().
I hope this PR can finally resolve https://github.com/MongoEngine/mongoengine/issues/1446. I reviewed that issue, the previous attempts to fix it (https://github.com/MongoEngine/mongoengine/pull/1457 and …
=> Breaking change: Improve save() performance by skipping index creation

docs/changelog.rst, mongoengine/base/fields.py, mongoengine/fields.py, tests/fields/test_binary_field.py, tests/fields/test_enum_field.py, tests/fields/test_fields.py, tests/fields/test_object_id_field.py
Work on top of https://github.com/MongoEngine/mongoengine/pull/2531
Main change on top of the original PR is to only cast EnumField to reduce the blast impact of this breaking change. In fact the initial PR was affecting (casting) other fields than just EnumField. It was also affecting for instance ListField(ObjectId).
PR also includes some unrelated things that I spot while investigating this (missing tests, etc)
=> [Clone] Fixing loading of EnumField inside ListField

docs/changelog.rst, docs/guide/mongomock.rst, mongoengine/connection.py, tests/test_connection.py, tests/test_connection_mongomock.py
Clone of #2729 with additional improvements
- changed connection_class to "mongo_client_class": although a bit more verbose I think it is more self-explanatory
- removed old way of integrating mongomock (i.e `connect(host="mongomock://localhost")`), this one is much better and less invasive as it removes all trace of mongomock from MongoEngine modules (mongomock only present in tests)
- Improve the doc
=> [Clone] Allow specifying alternative connection_class 

mongoengine/connection.py
This addresses #1168 (an old issue 😄).
This pull request opens door for projects like [montydb](https://github.com/davidlatwe/montydb) or [mongita](https://github.com/scottrogowski/mongita) that provids mongo-like alternative for testing or simple production usage, able to gain benefit from mongoengine.
There's some small amount of discussions in said projects:
https://github.com/scottrogowski/mongita/issues/4
https://github.com/davidlatwe/montydb/issues/64
And the only workaround for this is to monkey-patch `pymongo.MongoClient` just like what #1168 has concluded.
But thanks to the evolution that mongoengine has been through, the codebase seems able to enable this feature easily. Hance this PR.
Please let me know what you think, thanks.
=> Allow specifying alternative connection_class

mongoengine/base/datastructures.py, tests/document/test_delta.py
Only triggering `_mark_as_changed` on DictField if the value is actually
changed.
Limit the number of field accumulated in `_changed_fields`.
=> Fix: DictField are always marked as changed

mongoengine/queryset/base.py, tests/queryset/test_queryset.py, tests/queryset/test_queryset_aggregation.py
fix none() has no effect in update / aggregate / first
and cause query on all collection.
Not sure that this is the best solution for aggregation case
But this the best I found
=> fix none() has no effect in update/aggregate / first

mongoengine/connection.py
Here's an example of the server log behavior after this change:
```
{"t":{"$date":"2023-04-13T10:56:07.619-05:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:58812","uuid":"38175cc1-8c5c-44a2-8b05-afc38f35823e","connectionId":219,"connectionCount":8}}
{"t":{"$date":"2023-04-13T10:56:07.624-05:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn219","msg":"client metadata","attr":{"remote":"127.0.0.1:58812","client":"conn219","doc":{"driver":{"name":"PyMongo|MongoEngine","version":"4.2.0|0.27.0"}, ...}}}
```
This change helps identify mongoengine usage and version info for user reported issues.
=> Log MongoEngine version when connecting to the server

mongoengine/fields.py
x-ref: https://pillow.readthedocs.io/en/stable/releasenotes/2.7.0.html#antialias-renamed-to-lanczos
=> fix Pillow deprecation warning for Image.ANTIALIAS by using its new name

docs/changelog.rst, mongoengine/fields.py, tests/fields/test_embedded_document_field.py
Fixes https://github.com/MongoEngine/mongoengine/issues/2784
=> 2784_validate_override_embedded_doc

docs/changelog.rst, docs/guide/querying.rst, mongoengine/context_managers.py, mongoengine/queryset/base.py, tests/document/test_indexes.py, tests/test_context_managers.py
- Fix no_dereferencing context manager which wasn't turning off auto-dereferencing correctly in some cases
- Fix tests that were really broken (due to `__exit__` swallowing the exception) ...
- BREAKING CHANGE: no_dereferencing context manager no longer returns the class in __enter__
as it was useless and making it look like it was returning a different class.
This means it is now just `with no_dereferencing(User):` instead of `with no_dereferencing(User) as OtherUserClass:`
Fixes #2504
=> Various fix for no_dereferencing context manager

docs/changelog.rst, mongoengine/queryset/transform.py, tests/queryset/test_queryset.py
Fix combination of __raw__ and mongoengine syntax
=> Fix combination of __raw__ and mongoengine syntax

docs/changelog.rst, mongoengine/context_managers.py, mongoengine/queryset/base.py, tests/queryset/test_queryset.py
=> add __raw__ to order_by

docs/changelog.rst, docs/guide/querying.rst, mongoengine/queryset/base.py, tests/queryset/test_queryset.py
Add option to user array_filters in mongoengine
=> support for array_filters

.github/workflows/github-actions.yml, .github/workflows/install_mongosh.sh, .github/workflows/start_mongo.sh, tox.ini
This adds support for testing PyMongo 4.7.3 and PyMongo 4.8.0 to the CI system (GHA).
It also installs `mongosh` if MongoDB >= 6.0
=> Add pymongo 4.7 and pymongo 4.8 to the CI

.github/workflows/github-actions.yml, .readthedocs.yml
Latest builds of RTD were failing silently https://readthedocs.org/projects/mongoengine-odm/builds/
This should address it
=> fix RTD build error

docs/changelog.rst, mongoengine/fields.py, tests/queryset/test_field_list.py
MongoDB "gt" operator can be used with a list as value, this adds support for e.g
`SomeDoc.objects(some_list_field__gt=[1.0, 2.0])
`
Fixes #2814
=> allow_list_as_value_for_gte_lte_ne

mongoengine/base/document.py, mongoengine/document.py, tests/document/test_timeseries_collection.py, tests/utils.py
This pull request introduces support for timeseries collections in MongoEngine, addressing issue #2661. With the addition of a 'timeseries' option in the Document meta dictionary, users can now easily create and manage timeseries collections. This enhancement aligns with MongoDB 5.0's timeseries feature, providing better support for time-based data storage scenarios. Contributions welcome!
Closes #2661 (if applicable)
=> feat: Add Timeseries Collection Support

.github/workflows/github-actions.yml, mongoengine/connection.py, tests/fields/test_datetime_field.py, tests/queryset/test_queryset_aggregation.py, tests/test_connection.py, tox.ini
Resolve issue where _check_name moved files between pymongo 4.8.0 and 4.9. This updates the import path. Also updated are other private members that the test rely on and a couple imports (`database` and `mongo_client`) that now must be explicitly declared.
The `_check_name` function can now be found [here](https://github.com/mongodb/mongo-python-driver/blob/9df635f10276d92e26b39c8ba35243c1064a29dd/pymongo/database_shared.py#L24). 
This closes #2847 and obsoletes #2848
=> Update to support pymongo 4.9

.github/workflows/start_mongo.sh, entrypoint.sh, tests/test_context_managers.py
Resolves https://github.com/MongoEngine/mongoengine/issues/2841
* Fix test that was source of most failures
* Update max transaction lock time for local container entrypoint
* Update max transaction lock time for github action
---
The majority of failures appeared to be attributed with the
`test_exception_in_child_of_a_nested_transaction_rolls_parent_back` unit test.
To resolve this test, I borrowed the approach taken by the test just below it:
`test_exception_in_parent_of_nested_transaction_after_child_completed_only_rolls_parent_back`
which was already creating a function for the work under test and simply
trapping the TransientTractionError.
After resolving this, I found that the max transaction lock request timeout
parameter needed to be modified. After doing so and letting the test …
=> Address flaky transaction tests

mongoengine/queryset/base.py
propagate collation, hint, comment settings to corresponding PyMongo functions in update, delete and aggregate
I have implemented a simple fix for issue #2842 , but I'm not sure how to write test case.
=> propagate collation, hint, comment to PyMongo functions

mongoengine/base/datastructures.py, tests/test_datastructures.py
Fixes #2808
`list.clear` was added in Python 3.3
=> Call mark_as_changed_wrapper for `list.clear` on ListField

docs/changelog.rst, mongoengine/base/utils.py, mongoengine/document.py, tests/document/test_indexes.py
=> Fix text index on multiple fields , order independent 

docs/changelog.rst, mongoengine/queryset/base.py, tests/queryset/test_queryset.py
=> support .where() with modify (previously silently ignored)

.github/workflows/github-actions.yml, .github/workflows/install_mongo.sh, .github/workflows/install_mongosh.sh, .github/workflows/start_mongo.sh, README.rst, mongoengine/mongodb_support.py, setup.py, tests/document/test_indexes.py, tox.ini
Add support for MongoDB 8.0 and newer Pymongo versions for testing. Drop obsolete versions of mongo, python and pymongo.
Also, I improved the helper shell scripts a bit.
=> Add support for MongoDB 8.0 in CI

README.rst
- Added `import datetime` to ensure datetime functionality is available
- Replaced deprecated `datetime.datetime.utcnow()` with `datetime.datetime.now(datetime.timezone.utc)`
- Used lambda for dynamic evaluation of default datetime in BlogPost.posted field
=> refactor(models): add datetime import and replace deprecated utcnow

tests/document/test_instance.py
Adding the test cases from https://github.com/MongoEngine/mongoengine/pull/2438
=> Add test for deepcopy and regex
