docs/changelog.rst
tests/document/indexes.py

Fix #877: Fix tests for pymongo 2.8+

---

docs/changelog.rst
mongoengine/queryset/transform.py
tests/queryset/transform.py

Fix #766: Add support for  operator

---

docs/changelog.rst
mongoengine/base/datastructures.py
tests/fields/fields.py

Fix #866:  does not follow

---

AUTHORS
docs/changelog.rst
mongoengine/fields.py
tests/document/instance.py

Fix #864: ComplexDateTimeField should fall back to None when null=True

---

mongoengine/base/document.py

See the link to understand why this is a bad idea:
http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments

Use None instead of mutable arguments

---

docs/changelog.rst
mongoengine/base/datastructures.py
tests/fields/fields.py

fixes #595 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/917)

Fix #595: Support += and *= for ListField

---

README.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/941)

Remove support to PIL.

---

docs/changelog.rst
mongoengine/connection.py
tests/test_connection.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/967)

Override `authentication_source` by "authSource" in URI

---

docs/changelog.rst
mongoengine/base/fields.py
mongoengine/fields.py
mongoengine/queryset/transform.py
tests/queryset/queryset.py

Fixes #453
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/979)

fix-#453: Queryset update doesn't go through field validation

---

docs/guide/defining-documents.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/992)

Add primary_key notice in defining-documents doc according to issue #985

---

mongoengine/fields.py

More idiomatic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/894)

Use not in instead of not (x in y)

---

docs/guide/defining-documents.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1004)

spelling change definion to definition

---

README.rst

replace little object name HtmlPost with TextPost that is the one used on the example
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1012)

little object name fix

---

docs/changelog.rst
mongoengine/base/fields.py
mongoengine/fields.py
tests/queryset/queryset.py

Added test, was still failing, and implemented the good solution proposed in #517
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1018)

Respect no_dereference() on embedded docs containing Ref

---

AUTHORS
docs/changelog.rst
mongoengine/document.py
tests/document/instance.py

Submitting a PR for enhancement #991 (raising an exception in case a document save is prevented by save_condition instead of silently failing)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1005)

Raise error if save_condition fails #991

---

mongoengine/base/document.py
mongoengine/queryset/transform.py
tests/queryset/transform.py

Fixes #259
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1025)

Improve error message for invalid query

---

mongoengine/dereference.py
tests/test_dereference.py

Here is the PR ;-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1024)

Fix #1017 (document clash between same ids but different collections)

---

tests/queryset/queryset.py

Closes #530
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1027)

Added passing test to prove save and only problem was fixed

---

mongoengine/fields.py

Related to issue #497
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1030)

Improved doc for SequenceField

---

docs/changelog.rst
docs/guide/querying.rst
mongoengine/queryset/base.py
tests/fields/fields.py
tests/queryset/queryset.py

Does #300, finally!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1029)

Removed get_or_create() method, deprecated since 0.8

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/queryset.py

Fix #1008
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1037)

Added test and fix for delete with write_concern w:0

---

docs/changelog.rst
mongoengine/base/document.py
tests/document/dynamic.py

Fix #882
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1035)

Simplified lookup_field mechanic and allow dynamic lookup for more than two parts

---

docs/changelog.rst
docs/guide/querying.rst
mongoengine/queryset/transform.py
tests/queryset/geo.py
tests/queryset/queryset.py
tests/test_connection.py

Fix #831 and completes #860 
Also simplifies geo query son code generation
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1036)

Added test, doc to implementation of min_distance query

---

AUTHORS
docs/changelog.rst
mongoengine/base/fields.py
tests/fields/fields.py

Fixes #705 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1014)

Allow to add custom metadata to fields

---

mongoengine/connection.py
tests/test_connection.py

see #1069
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1093)

Replace disconnect with close method in pymongo

---

mongoengine/queryset/base.py

Corrected the docstring for `mongoengine.queryset.base.update_one()`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1134)

docstring correction

---

mongoengine/base/fields.py
tests/document/instance.py

This pull-request fix false positive tests on ``_instance`` attribute and fix ``_instance`` attribute on lists of EmbeddedDocuments.
There are some open and  closed issues on subject: #63 #914 #660
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1131)

Fix instance back references

---

mongoengine/document.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1161)

Fixed a couple of documentation typos

---

mongoengine/errors.py

fix for issue #1164
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1165)

Add SaveConditionError to __all__

---

AUTHORS
docs/changelog.rst
mongoengine/__init__.py
mongoengine/queryset/base.py
tests/queryset/queryset.py

As described in #1157 - this is a proposed additional method on BaseQuerySet.
Not really sure what to do about versioning but I think I've followed the guidelines for contributing otherwise.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1167)

Upsert one

---

docs/guide/mongomock.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1198)

fix missing quote in /docs/guide/mongomock.rst

---

README.rst

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1205)

add highlight for python code

---

mongoengine/connection.py

May be this fix also resolve issue #1108
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1123)

Fixed detection of shared connections

---

mongoengine/queryset/base.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1220)

fixed minor typo in docstring

---

mongoengine/queryset/base.py
tests/test_signals.py

this commit fixes #578
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1196)

Fix pre_bulk_insert signal

---

AUTHORS
docs/changelog.rst
mongoengine/fields.py
tests/document/indexes.py
tests/fields/fields.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1254)

Fix long fields python3

---

mongoengine/dereference.py
tests/fields/fields.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1267)

Fix MapField in order to handle unicode keys.

---

mongoengine/queryset/queryset.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1289)

Fix typo in the docstring for __len__

---

AUTHORS
docs/changelog.rst

Update changelog for #1304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1307)

Update changelog for #1304

---

mongoengine/queryset/base.py

as suggested in https://github.com/MongoEngine/mongoengine/issues/1327#issuecomment-229338277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1328)

better description for upsert arg on some methods

---

docs/guide/defining-documents.rst

fix typo at docs/guide/defineing-documents.rst

---

docs/guide/querying.rst

Fix array-slicing documentation

---

mongoengine/fields.py
tests/fields/fields.py

see issue #892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1334)

Raise DoesNotExist when dereferencing unknown document

---

README.rst

Hi,
I could not execute the example as it is in the readme.
Would you welcome this changes in the example? Thisway one could quickly reproduce the results shown.
Thanks in advance!

fixes example

---

mongoengine/connection.py
tests/test_connection.py

This attempts to fix the same issues that #731 did, but in a much nicer way (and with better test coverage). Basically, it lets you create an authenticated connection via `connect(host='mongodb://localhost/db_name', username='user', password='pass')`. In the past, this would result in the credentials being dropped silently.
@ThisGuyCodes since you opened the original PR, I think you might be interested in it. @lafrech could you also take a look please?

Don't let the MongoDB URI override connection settings it doesnt explicitly specify

---

mongoengine/fields.py
mongoengine/queryset/transform.py
setup.cfg
tests/fields/fields.py

Fixes #560 (see https://github.com/MongoEngine/mongoengine/issues/560#issuecomment-264737943 for a longer description of what's happening here and how this PR is implemented).

Add ability to filter the generic reference field by ObjectId and DBRef

---

.travis.yml
mongoengine/python_support.py

Deprecate Python v2.6

---

AUTHORS
docs/changelog.rst
mongoengine/fields.py
tests/fields/fields.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mongoengine/mongoengine/1265)

DecimalField force_string rounding fix.

---

README.rst

Closes #1342 
@lafrech @rozza @thedrow are you ok with this change? After a bit of a test run I think I can do it long-term and I believe I can contribute a lot to the project. At my company we're running 2 big services using MongoDB (v3.0 and v3.2) and MongoEngine (one using our own fork and one using the latest upstream version), so I have quite a strong incentive to make this package better.

Update the maintainer

---

docs/guide/querying.rst

The current documentation does not indicate properly where Q is defined.

Update documentation to include Q definition

---

mongoengine/queryset/transform.py
tests/queryset/queryset.py

Fixes #702 
Personally I don't care much for it and wouldn't mind if dec was removed all together (negative inc works perfectly fine), but since we already support it, might as well make it work correctly.

Support a negative dec operator

---

mongoengine/base/common.py
tests/document/instance.py

Add a $rename operator

---

tests/test_connection.py

Test connection's write concern

---

mongoengine/base/datastructures.py

[#1459] fix typo `__neq__` to `__ne__`

---

docs/changelog.rst
docs/guide/defining-documents.rst
mongoengine/base/fields.py
tests/fields/fields.py
tests/fields/file_tests.py
tests/utils.py

PR is related to issue #1481
It allows the choices parameter (StringField(choices=...)) to be a set and not only a tuple or list

allow to use sets in choices StringField(choices=...)

---

mongoengine/connection.py
tests/test_connection.py

Test and document controlling the size of the connection pool

---

mongoengine/base/document.py
tests/fields/fields.py

Respect db fields in multiple layers of embedded docs

---

mongoengine/queryset/base.py

There was lots of unnecessary logic in there.

Cleanup BaseQuerySet.__getitem__

---

docs/tutorial.rst

`john` was an undefined variable. To prevent a NameError, I have prompted the user to create the variable `john`.

Prevent NameError: name 'john' is not defined

---

AUTHORS
mongoengine/connection.py

append contributor in CONTRIBUTING;
change more efficient set construction to set literal

contributor;change set function to set literal

---

AUTHORS
docs/guide/querying.rst
mongoengine/queryset/transform.py
tests/document/instance.py
tests/queryset/modify.py
tests/queryset/queryset.py

support position in 'push' #1565

---

mongoengine/queryset/transform.py
tests/document/instance.py
tests/queryset/queryset.py

use each modifier only with $position  #1673

---

docs/changelog.rst
mongoengine/base/document.py
mongoengine/dereference.py
mongoengine/fields.py
setup.cfg
tests/fields/fields.py
tests/queryset/queryset.py

fix validation error for invalid embedded document instance #1067

---

tests/fields/fields.py
tests/queryset/geo.py
tests/queryset/queryset.py

When I was trying to write tests to increase code coverage, I found a bug from missing tests in code coverage report.(I will report a bug that I found).

add tests to increase code coverage

---

tests/document/instance.py

Added a test for reverse_delete_rule with pull anyway due to increase test coverage.

add test case for reverse_delete_rule with pull #1519

---

tests/document/class_methods.py

Add testcase for #1751

---

mongoengine/document.py

use MongoClient.is_mongos in ensure indexes #1759

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/queryset.py

remove deprecated insert method.

use insert_one, insert_many and remove deprecated one #1491

---

AUTHORS
mongoengine/base/datastructures.py
tests/test_datastructures.py

fix BaseList.__iter__ operator + minor improvements

---

mongoengine/base/document.py
tests/document/instance.py
tests/queryset/queryset.py

Did my best to describe the 'created' argument but it may be too detailed. Let me know what you think
Relates to #1854

Document the 'created' attribute of .from_json

---

mongoengine/document.py

Fix .delete doc of **write_concern

---

mongoengine/fields.py

Duplicate of #1698 to have it merged faster

Fix string formatting bug in ReferenceField.validate

---

mongoengine/fields.py

Fixed format string issue in mongoengine error message.

---

mongoengine/connection.py
tests/test_connection.py

parse read_preference from conn_host #1665

---

mongoengine/queryset/base.py
mongoengine/queryset/queryset.py

Clone of PR #1680 to force CI
Fixes #1641

CLONE - return instead of raising StopIteration

---

docs/guide/defining-documents.rst

Updating inheritance doc

---

docs/upgrade.rst
mongoengine/base/common.py
mongoengine/base/datastructures.py
mongoengine/base/document.py
mongoengine/base/metaclasses.py
mongoengine/base/utils.py
mongoengine/document.py
mongoengine/errors.py
mongoengine/fields.py
mongoengine/queryset/base.py
mongoengine/queryset/queryset.py
mongoengine/queryset/transform.py

Fixes some of the findings of Pylint

Improve code quality (mainly based on pylint findings)

---

mongoengine/base/document.py
mongoengine/python_support.py

Fix deprecation warning about Hashable in py3.7

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/queryset.py

Fixes #1919 
+ reorganized the tests of the bulk insert
+ minor styling fixes in that test

Update the ids of the given documents during bulk insert

---

docs/guide/querying.rst

fix some asserts in no_dereference doc

---

docs/changelog.rst
mongoengine/base/document.py
mongoengine/queryset/base.py
setup.cfg
tests/fields/fields.py

Fixes #1934 (More details in ticket)

Fix bug when doing modifications to generic-referenced document

---

docs/changelog.rst
mongoengine/__init__.py
mongoengine/dereference.py

@erdenezul Let me know if you are fine with this changelog. Once I have the green light, I'll push the 0.16.0 tag

Bump version to 0.16.0 + update changelog

---

mongoengine/queryset/base.py
tests/queryset/queryset.py

Aggregate gives wrong results on when used with a queryset having limit and skip.
Fixing as per https://stackoverflow.com/a/24161461

Fix limit usage in aggregate

---

mongoengine/base/metaclasses.py
mongoengine/common.py
mongoengine/errors.py
mongoengine/fields.py
mongoengine/queryset/base.py
mongoengine/queryset/transform.py
tests/document/indexes.py
tests/document/instance.py
tests/fields/geo.py
tests/fields/test_cached_reference_field.py
tests/fields/test_datetime_field.py
tests/fields/test_email_field.py
tests/fields/test_lazy_reference_field.py
tests/fields/test_long_field.py
tests/queryset/queryset.py
tests/queryset/transform.py
tests/test_common.py
tests/test_context_managers.py
tests/test_datastructures.py

I looked at the coverage report in order to identify dead code and places where coverage could be improved
Relates to #1945

Improve test cov

---

mongoengine/connection.py
mongoengine/document.py
mongoengine/pymongo_support.py
mongoengine/queryset/base.py
mongoengine/queryset/transform.py
tests/queryset/queryset.py
tests/test_connection.py
tests/test_replicaset_connection.py
tests/utils.py

- remove dead code (related to pymongo2)
- minor cleaning

remove dead code (related to pymongo2)

---

mongoengine/fields.py
mongoengine/mongodb_support.py
tests/document/instance.py
tests/fields/test_datetime_field.py

- slightly improved code for parsing date + increase its test cov
- added test related to shard_key_routing (ported from mongomallard)
Relates to #1945

minor refactoring and additional of tests

---

docs/guide/defining-documents.rst

Document the custom field validation feature

---

.travis.yml

add pypy3 back to travis and improve python 3.7 integration

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/queryset.py

See the detailed commit messages. I tried to provide all the context/rationale in there.

Better management of the automatic "_cls" field

---

mongoengine/fields.py

So small, I nearly missed it... :)

Fix small typo

---

docs/changelog.rst
mongoengine/errors.py
mongoengine/queryset/base.py

Change misleading error message

---

docs/guide/querying.rst

Document Model.objects.aggregate entrypoint with an example

---

mongoengine/base/document.py

Fix docstring format to improve pycharm inspection

---

docs/changelog.rst
docs/guide/index.rst
docs/guide/logging-monitoring.rst

Documented how pymongo.monitoring can be used with MongoEngine

---

AUTHORS
docs/changelog.rst
mongoengine/queryset/visitor.py
tests/document/test_instance.py
tests/queryset/test_visitor.py

close MongoEngine/mongoengine#2203

Add __eq__ to Q and Q operations

---

mongoengine/context_managers.py
tests/document/test_instance.py

Added alias parameter in query_counter

---

docs/changelog.rst
mongoengine/queryset/base.py
mongoengine/queryset/visitor.py
tests/queryset/test_visitor.py

close MongoEngine/mongoengine#2209
Also, as you are here please check out my issue about a small refactor regarding filters: https://github.com/MongoEngine/mongoengine/issues/2211

Add __bool__ to Q and QCombination

---

docs/guide/defining-documents.rst

I thought I would add some explanation on how querying works when using inheritance and the additional _cls attribute. In fact once you start playing with inheritance, knowing about `_cls` can be helpful

provide additional details on how inheritance works in doc

---

docs/changelog.rst
mongoengine/__init__.py

Let's do a release as there is a bug in 0.18.2 preventing users from migrating to Mongo 4.2
closes #2220

Release 0 19 0

---

docs/guide/gridfs.rst

Mainly emphasizing that subsequent calls to read() requires to rewind the file with seek(0)

improve doc of GridFS

---

docs/upgrade.rst

Fix simple typo: thorougly -> thoroughly

---

.travis.yml
README.rst
docs/changelog.rst
tox.ini

Mongodb 40

---

mongoengine/document.py
mongoengine/queryset/base.py
tests/fields/test_complex_datetime_field.py

Fix invalid escape seq in codebase

---

docs/changelog.rst
mongoengine/base/fields.py

Was marked as deprecated years ago

Remove name param in Field constructor (replaced by db_field)

---

docs/changelog.rst
mongoengine/queryset/base.py

remove 2 methods that were deprecated a while ago but never removed

[>= 0.19.0] Remove old deprecated method

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/test_queryset.py

Improve error message to make it more performant and also less confusing in case of race conditions in the threads
Closes #630

Improve MultipleObjectsReturned message from queryset.get

---

docs/changelog.rst
setup.py

I believe it was put in "beta" a while ago and then everyone forgot about changing the classifier :)

Bump development status classifier

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/test_queryset.py

Fix bug with Doc.objects.limit(0) which should return all docs

---

mongoengine/document.py

fix py3 incompatible code

---

.travis.yml
tox.ini

Update versions of main libraries used in travis CI

Upgrade pymongo and mongodb versions used in CI

---

docs/changelog.rst
mongoengine/base/datastructures.py
tests/document/test_delta.py
tests/document/test_instance.py
tests/fields/test_dict_field.py
tests/fields/test_fields.py
tests/fields/test_geo_fields.py
tests/test_datastructures.py

Fixes #2392
+ minor improvements in existing test assertions

Fix listfield change detection of index 0

---

AUTHORS
docs/changelog.rst
docs/guide/defining-documents.rst
mongoengine/fields.py
tests/fields/test_enum_field.py

Seems that this is dead: https://github.com/MongoEngine/mongoengine/pull/2348
And there is no willing to finish this up
Thus, I made a new PR, also wrote more tests, added some example usages
It is my first PR here, hope all is fine

Add EnumField

---

docs/changelog.rst
mongoengine/base/document.py
mongoengine/queryset/base.py
tests/document/test_instance.py

After some investigations, I realized that most of the code added in the commit below seems to have no effect at all. https://github.com/MongoEngine/mongoengine/commit/e00891997

Removed code related to Document.__only_fields

---

docs/guide/connecting.rst

Document fact that srv URI can be used with host #1956

---

docs/Makefile
docs/guide/index.rst
docs/guide/migration.rst

Add migration documentation

---

docs/changelog.rst
mongoengine/__init__.py

Fixes #2410
bump version + update changelog

Prepare 0.21.0 release

---

docs/guide/gridfs.rst
mongoengine/base/fields.py
mongoengine/connection.py
mongoengine/document.py
mongoengine/fields.py
mongoengine/queryset/base.py
mongoengine/queryset/queryset.py

+ remove versionadded/changed as it's not maintained

Improve Fields documentation

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/document/test_instance.py
tests/queryset/test_transform.py

Fixes #2425
Credit goes to @daitakahashi for this

Use Queryset._query instead of Cursor.__spec for count()

---

tests/test_connection.py
tests/test_connection_mongomock.py

Improve mongomock tests to avoid regression

---

.github/workflows/github-actions.yml

minor improvement to github actions flow

improve github actions

---

.github/workflows/github-actions.yml

coveralls is broken since it received a major update

Fix coveralls in CI

---

mongoengine/queryset/base.py
tests/queryset/test_queryset.py
tests/utils.py

Feature: "allow_disk_use"

---

.github/workflows/github-actions.yml
.github/workflows/install_mongo.sh
.github/workflows/start_mongo.sh
docs/changelog.rst
mongoengine/mongodb_support.py
mongoengine/queryset/base.py
tests/document/test_indexes.py
tests/queryset/test_queryset.py
tests/utils.py

Add Mongodb 44 ci and fix incompat

---

docs/changelog.rst
docs/guide/connecting.rst

improve connect() doc and put more emphasis on URI string

---

docs/guide/defining-documents.rst
mongoengine/fields.py

Fix one-to-many example that is actually a many to many

---

AUTHORS
docs/changelog.rst
mongoengine/base/document.py
tests/fields/test_lazy_reference_field.py

I'm not sure how complete this fix is.

Test case and proposed solution for #2484

---

docs/guide/migration.rst

Hi,
Just a correction of typo.
regards,

Typo correction

---

docs/apireference.rst
docs/guide/defining-documents.rst
mongoengine/connection.py
mongoengine/context_managers.py
mongoengine/fields.py
tests/fields/test_fields.py

Fix EnumField doc
+ improved query_counter doc by providing an example

fix doc formatting (enumfield, etc)

---

AUTHORS
docs/changelog.rst
mongoengine/fields.py
tests/fields/test_decimal_field.py

Built on top of #2535, simply adding test cases

Fix decimal field precision0

---

docs/guide/querying.rst

Minor typo error

---

AUTHORS
docs/guide/querying.rst
tests/queryset/test_queryset.py

add update operator to documentation
and add rename operator tester

add update operator to documentation

---

README.rst
docs/Makefile

So that it s up to date regarding MongoDB supported versions (tested in CI)
Fixes #2588

Update README with supported mongodb versions

---

docs/changelog.rst

elaborate_authentication_breaking_change_authsource

---

.pre-commit-config.yaml
docs/requirements.txt

Noticed when rebasing my branch on current master. 
* Fixing doc building based on [this](https://github.com/sphinx-doc/sphinx/issues/10291#issuecomment-1078046986) solution.
* Fixing linting through [this](https://github.com/psf/black/issues/2964)

Fixing linting and doc building upgrading dev dependencies

---

.pre-commit-config.yaml
docs/changelog.rst
mongoengine/connection.py
tests/test_connection.py

Work on top of https://github.com/MongoEngine/mongoengine/pull/2653 to fix the tests

Mcsheehan 2507 support mongodb aws

---

docs/guide/connecting.rst

Add a note about inheritance and switch_db

Update connecting.rst - Add a note about inheritance and switch_db

---

docs/guide/validation.rst

Fix the NameError in this example

update docs/guide/validation.rst example

---

docs/changelog.rst
mongoengine/connection.py
tests/test_connection.py

clone of PR with conflict fixed

Clone - Shane harvey fix disconnect closes clients too early

---

docs/changelog.rst
mongoengine/connection.py
tests/test_connection.py

PyMongo 4 bug fix: don't preemptively close in use client

---

docs/changelog.rst
mongoengine/document.py
mongoengine/fields.py
tests/fields/test_decimal128_field.py

Polishing on top of https://github.com/MongoEngine/mongoengine/pull/2521

[Clone] implement Decimal128Field 

---

mongoengine/fields.py
tests/fields/test_decimal128_field.py

Perhaps this have been named `NumberDecimalField`?
updates #1981 
ping @janste63

implement Decimal128Field

---

mongoengine/base/fields.py
mongoengine/fields.py
tests/fields/test_enum_field.py

Under certain condition, inside value of ListField(EnumField) don't get casted to the proper Enum. This patches fixes that.

Fixing loading of EnumField inside ListField

---

docs/changelog.rst
mongoengine/base/document.py
mongoengine/base/fields.py
mongoengine/document.py
mongoengine/fields.py
tests/document/test_instance.py
tests/fields/test_complex_datetime_field.py
tests/fields/test_decimal_field.py
tests/fields/test_float_field.py
tests/fields/test_object_id_field.py
tests/queryset/test_modify.py
tests/queryset/test_queryset.py
tests/test_connection_mongomock.py
tests/test_pymongo_support.py

Work on top of https://github.com/MongoEngine/mongoengine/pull/2682
- Moved the original logic in Added null check for Issue (more consistent with similar logic in other fields)
- fixed ComplexDateTime that had the same issue although never reported
+ improve test coverage of unrelated feature

Work on top of "Added null check for Issue"

---

mongoengine/base/fields.py

Added null check for Issue # 2681

---

.github/workflows/github-actions.yml
docs/changelog.rst
mongoengine/queryset/transform.py
tests/queryset/test_transform.py

Work on top of #1351
Changes:
- reworked the code and added extensive doc
- added tests case

Clone - FIx for update on field with operator name

---

mongoengine/queryset/transform.py

fix bugs which cause cannot modify field `type` etc.

fix: check parts length before get match

---

docs/changelog.rst
mongoengine/base/datastructures.py
tests/document/test_delta.py

Clone of https://github.com/MongoEngine/mongoengine/pull/2606, adding minor things on top

CLONE - (Jaesivsm) mark dict field as dirty

---

mongoengine/base/datastructures.py
mongoengine/base/document.py
mongoengine/fields.py
tests/fields/test_datetime_field.py
tests/queryset/test_queryset.py

- simplify LongField
- add tests cov
- remove unnecessary conditions

Minor improvements

---

docs/changelog.rst
mongoengine/queryset/base.py
tests/queryset/test_queryset.py
tests/queryset/test_queryset_aggregation.py

Clone of #2669, adding minor polishing on top

[CLONE] Idoshr fix none queryset run on all collection

---

docs/guide/querying.rst

Document string operator on ListField

---

mongoengine/base/document.py
mongoengine/connection.py
mongoengine/pymongo_support.py
mongoengine/queryset/base.py

Update uuidRepresentation warnings with "unspecified" as the future default

---

docs/changelog.rst
mongoengine/connection.py
tests/test_connection.py

Accept uuidrepr in URI

---

.github/workflows/github-actions.yml
.github/workflows/install_mongo.sh
README.rst
docs/changelog.rst
mongoengine/mongodb_support.py
tests/document/test_indexes.py
tox.ini

Add MongoDB 6.0 and 7.0 to the GH Actions CI pipeline.

Add mongodb 6.0 and 7.0 to the CI pipeline

---

docs/changelog.rst
mongoengine/connection.py
tests/test_connection.py

Add support for readPreferenceTags in connection parameters #2644

---

docs/guide/querying.rst

add missing link for set_on_insert in documentation

---

docs/changelog.rst
mongoengine/base/document.py
mongoengine/queryset/base.py
tests/queryset/test_queryset.py

add ability to turn off text_score computation on search_text call

---

docs/changelog.rst
mongoengine/__init__.py
mongoengine/context_managers.py
tests/test_context_managers.py

bug was introduced in 0.28.0
Fixes #2799

Fix bug in mutable thread local related with no_dereference ctx manager

---

.github/workflows/github-actions.yml
docs/changelog.rst
mongoengine/__init__.py
mongoengine/connection.py
setup.py
tox.ini

Fix pymongo37 incompatibility

---

mongoengine/base/datastructures.py
tests/fields/test_embedded_document_field.py

Improvement over https://github.com/MongoEngine/mongoengine/pull/2821

Fix weakref in EmbeddedDocumentListField

---

mongoengine/base/datastructures.py

Add missing weakref.proxy

---

mongoengine/queryset/base.py
tests/queryset/test_queryset.py

#2811 - Add array filter to modify

#2811 - Add array filter to modify

---

docs/changelog.rst
tests/document/test_instance.py
tests/fields/test_binary_field.py
tests/queryset/test_queryset.py
tests/queryset/test_queryset_aggregation.py
tests/utils.py

Adding tests on top of https://github.com/MongoEngine/mongoengine/pull/2843
Fixes https://github.com/MongoEngine/mongoengine/issues/2842

set more support for collation hint comment (Winedays feature/query )

---

docs/changelog.rst

Documenting https://github.com/MongoEngine/mongoengine/pull/2858 in changelog

update changelog with list .clear change
